jenkinsci/git-client-plugin

.gitignore
src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/JGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/MergeCommand.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java

I would like to help provide the feature requested in https://issues.jenkins-ci.org/browse/JENKINS-12402 as I need the same feature. I am starting by editing the git-client-plugin and I would like a review please. Specifically, I added a @Bug(12402) to the first new test I added, but is that appropriate? Also, I have not found where to add a test for the CliGitApiImpl, I only found where to add tests for the JGit implementation. Your feedback and comments are welcome.

Ability to use all fast forward modes available

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/JGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/Netrc.java

Had few minutes to look on results. Maybe will be useful.

small improvements based on analysing tools

---

src/main/java/org/jenkinsci/plugins/gitclient/JGitAPIImpl.java

If JGit PushCommand call() returns without an exception, it does generally not mean all / any items have been pushed successfully. PushResult has to be evaluated to be sure.

Added PushResult evaluation

---

pom.xml
src/main/java/org/jenkinsci/plugins/gitclient/Netrc.java

It will allow to setup FindBugs reporting or to enforce the code requirements on https://jenkins.ci.cloudbees.com/job/plugins/job/git-client-plugin/

Enable FindBugs report generation on verify stages

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java

The BuildData pruning step which Nicholas de Loof added in [c1872](https://github.com/jenkinsci/git-plugin/commit/c1872d038cc2f584bafbc375744deb54a1dbe316) of the git plugin calls the getBranches() method of the git client plugin to list all branches so they can be evaluated for possible removal from BuildData.  Removing excess data from BuildData is a good thing.  
Unfortunately, the getBranches() method calls `git rev-parse` for each branch in the repository. With a small number of branches, that is not a problem.  With a large number of branches, it is a big problem.
Thankfully, the parseBranches method already included a suggestion for the fix.  Instead of calling `git rev-parse` for each branch in the repository, it makes a single call to `git branch -v` and then parses the output to …

Fix JENKINS-32258 - many rev-parse calls pruning remote tracking branches

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/GitClient.java
src/main/java/org/jenkinsci/plugins/gitclient/JGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/RemoteGitImpl.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java

Changes to support git-plugin:
https://issues.jenkins-ci.org/browse/JENKINS-31326

Add showRevision(from,to,excludeCommitFiles) to support JENKINS-31326

---

pom.xml
src/main/java/hudson/plugins/git/GitTool.java
src/main/java/org/jenkinsci/plugins/gitclient/JGitTool.java

[JENKINS-37391](https://issues.jenkins-ci.org/browse/JENKINS-37391)
cc @reviewbybees

[FIXED JENKINS-37391] Added @Symbols for GitTool and JGitTool

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java

The SSH_ASKPASS script was being setup improperly on windows since
it was echoing quotes as well as the actual echo command itself
since `@echo off` was not being specified.

[JENKINS-20356] Fix SSH_ASKPASS on windows

---

src/test/java/org/jenkinsci/plugins/gitclient/jgit/PreemptiveAuthHttpClientConnectionTest.java

Test had an Ignore annotation which incorrectly states that the test does not work.

Don't ignore a URIish test - works as expected

---

src/test/java/org/jenkinsci/plugins/gitclient/GitTest.java

Remove another dependency on full depth repository.

Use HEAD as expected commit in GitTest

---

pom.xml
src/test/java/hudson/plugins/git/GitToolTest.java

@reviewbybees needed, update to the same structs version as used by git plugin, and use latest objenesis release.

Use latest dependencies

---

src/main/java/org/jenkinsci/plugins/gitclient/JGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/PushCommand.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java

Detected differences between command line git versions, and a surprising difference between JGit and CliGit.
@reviewbybees requested (though this is test code and an import fix, low risk)

Test more cases of fetch options

---

src/test/java/org/jenkinsci/plugins/gitclient/CredentialsTest.java

Want to test both methods, but don't want to execute every test for
every combination of method arguments.
@reviewbybees

Use one of two similar methods to add a credential to test

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/JGitAPIImpl.java

@reviewbybees @MarkEWaite Adding logging to show that the clone points to a reference repository

[JENKINS-46737] Improve logging when linking a reference repository.

---

pom.xml

See https://projects.eclipse.org/projects/technology.jgit/releases/4.5.4
for details.
Fix some cases of incorrect handling of NFS file locking.

Use JGit 4.5.4

---

Jenkinsfile
README.md
pom.xml
src/main/java/hudson/plugins/git/GitTool.java
src/main/java/hudson/plugins/git/Revision.java
src/main/java/org/jenkinsci/plugins/gitclient/AbstractGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/JGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/LegacyCompatibleGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/Netrc.java
src/main/javadoc/overview.html
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientTest.java

Depend on Jenkins LTS 2.60.1.
Test in Jenkinsfile with Jenkins 2.60.1 and 2.89.1.
Request review from @jenkinsci/code-reviewers

Use Jenkins 2.60.1 and JDK 8

---

src/main/java/hudson/plugins/git/GitAPI.java
src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/GitClient.java
src/main/java/org/jenkinsci/plugins/gitclient/JGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/RemoteGitImpl.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java

See bug report https://issues.jenkins-ci.org/browse/JENKINS-26660 for more details

Clean takes a flag that will add a --force flag to clean.

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java

Please take a look at this (blind, but simple) change.  Hopefully this helps make some progress on JENKINS-48258.

[JENKINS-48258] add distinctive temp file prefix to aid debugging

---

pom.xml
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java

Use the most recent JGit release, and update several other components.

Use JGit 4.11.0

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/test/java/org/jenkinsci/plugins/gitclient/CredentialsTest.java

[JENKINS-50573] Adapt to openssh 7.7 arg precedence change

---

Jenkinsfile
pom.xml

Use sshd 2.4 in test
Not a compile time dependency

Use Jenkins 2.107.3 for compatibility test

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java

Jenkins 48258 busy ssh text file fix - As per JENKINS-48258 comments.

Jenkins 48258 busy ssh text file fix

---

pom.xml

Update of a component used for tests.

Use equalsverifier 2.4.6

---

src/test/java/hudson/plugins/git/GitToolTest.java
src/test/java/hudson/plugins/git/IndexEntryTest.java
src/test/java/hudson/plugins/git/RevisionTest.java
src/test/java/hudson/plugins/git/TagTest.java
src/test/java/org/jenkinsci/plugins/gitclient/CliGitAPIImplAuthTest.java
src/test/java/org/jenkinsci/plugins/gitclient/CliGitAPIImplTest.java
src/test/java/org/jenkinsci/plugins/gitclient/CliGitAPITempFileTest.java
src/test/java/org/jenkinsci/plugins/gitclient/CliGitCommand.java
src/test/java/org/jenkinsci/plugins/gitclient/CredentialsTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitURIRequirementsBuilderTest.java
src/test/java/org/jenkinsci/plugins/gitclient/LegacyCompatibleGitAPIImplTest.java
src/test/java/org/jenkinsci/plugins/gitclient/LogHandler.java
src/test/java/org/jenkinsci/plugins/gitclient/LogHandlerTest.java
src/test/java/org/jenkinsci/plugins/gitclient/NetrcTest.java
src/test/java/org/jenkinsci/plugins/gitclient/RemotingTest.java
src/test/java/org/jenkinsci/plugins/gitclient/StringSharesPrefix.java
src/test/java/org/jenkinsci/plugins/gitclient/WarnTempDirValueTest.java
src/test/java/org/jenkinsci/plugins/gitclient/jgit/PreemptiveAuthHttpClientConnectionTest.java
src/test/java/org/jenkinsci/plugins/gitclient/trilead/CredentialsProviderImplTest.java
src/test/java/org/jenkinsci/plugins/gitclient/trilead/StandardUsernamePasswordCredentialsImpl.java

Tests have been updated to be a bit more consistent. There are no functional changes.

Cleanup Tests

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/test/java/org/jenkinsci/plugins/gitclient/CredentialsTest.java

Merges changes from the stable-2.7 branch onto the master branch and makes minor changes as needed to adapt to the master branch.
@reviewbybees please and @richbg as well.

Fix JENKINS-50573 on master branch

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/test/java/org/jenkinsci/plugins/gitclient/CredentialsTest.java

@reviewbybees please.  @richbg as well.

Fix JENKINS-50573 on stable-2.7 branch

---

src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java

This is a follow-up to de9da9a7f942e113b919b200b1811332acdb6aeb.

Improve tests that are system locale dependent

---

src/test/java/org/jenkinsci/plugins/gitclient/CredentialsTest.java

Reduce CredentialsTest differences between stable-2.7 and master
branch

Add @Issue annotations to CredentialsTest

---

pom.xml

To address https://issues.jenkins-ci.org/browse/JENKINS-53121

Update surefire plugin version to 2.21.0

---

src/test/java/hudson/plugins/git/GitToolTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java
src/test/java/org/jenkinsci/plugins/gitclient/PushTest.java

@darxriggs thanks for suggesting the improvement using Hamcrest assertions.  Would love to have your review for clarity and consistency,

Use Hamcrest assertions for clearer code

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java

Hi all,
I made git-client-plugin to work with z/OS Unix System Service with command line git implementation made by Rocket SW as it has addons to work correctly under z/OS unix. I had it running successfully almost for one year and decided to offer my changes to community. Most code changes in this PR are related to the transcoding input/output from git cli from/to IBM z/OS EBCDIC code page. Kindly let me know if this PR can be accepted and what should i amend/changed to get this PR accepted.
PS: This PR is for master branch (3.0.0) - same as in PR #361

z/OS Unix System services CLI git enablement

---

src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java

Also replaces two assertTrue with better messages and easier reading using a Hamcrest assertion.

Remove duplicate method

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/JGitAPIImpl.java

* Make all instance variables private in all Command implementations
* Use @Override on all implemented methods in all Command implementations

Command improvements

---

.mvn/extensions.xml
pom.xml

Thanks @markewaite :gift: :smile:

Update to latest parent pom and incrementals-tools

---

pom.xml

Include latest JGit 5.2 bug fix release

Use JGit 5.2.1, parent pom 3.32, and latest equalsverifier

---

src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java

It is bad form to rely on space as a command separator.  It breaks tests when running in an environment where the test directory path includes a space.  It makes it harder to pass significant spaces as arguments.
Special thanks to @thomasgl-orange for detecting the problem in #393 .
More changes will be needed before spaces in paths work completely in tests.

Stop separating test command arguments with spaces

---

pom.xml

Use latest version of equalsverifier.

Test with equalsverifier 3.1.9

---

Jenkinsfile

Use the buildPlugin recommended configuration to test the plugin.  Will test with Java 11 and Java 8 using current pom Jenkins version and most recent LTS version

Test with buildPlugin recommended configuration

---

pom.xml

Use parent pom 3.44

---

pom.xml

Use the most recent JGit release.

Update JGit from 5.3.2 to 5.4.0

---

pom.xml
src/test/java/org/jenkinsci/plugins/gitclient/CliGitAPITempFileTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientTest.java

Update to the most recent parent pom.

Use parent pom 3.45

---

pom.xml

Use the latest Apache commons-text package in testing.  Not a production dependency, just test.

Test with commons-text 1.7

---

pom.xml

* [Release notes](https://projects.eclipse.org/projects/technology.jgit/releases/5.4.2)
Use [JGit 5.4.2](https://projects.eclipse.org/projects/technology.jgit/releases/5.4.2)

Use JGit 5.4.2

---

src/test/java/org/jenkinsci/plugins/gitclient/GitClientSecurityTest.java

CLI git older than 1.9 does not fully support the "--" separator between options and operands.
Not an issue execpt when remote URL check is disabled.
Resolved by detecting the special case and enabling remote URL check even if it was disabled.

Protect git 1.8.3 and earlier test cases

---

src/test/java/org/jenkinsci/plugins/gitclient/GitClientSecurityTest.java

When the Jenkins command line argument disables repository sanity checks, the security problem from SECURITY-1534 is visible in some cases.  Adapt tests to those cases.
[SECURITY-1534](https://jenkins.io/security/advisory/2019-09-12/) reports that repository URL's provided by the user were not sanity checked before being passed to git ls-remote and git fetch. A sanity check is now enabled by default.
As a backwards compatibility 'escape hatch', a Jenkins command line argument can disable the repository sanity checks. Disabling the checks then relies on command line git to perform the sanity checks.
GitClientSecurityTest uses a randomly selected value to enable or disable the repository URL check. If the repository check is selected to be disabled and the command line git implementation …

Better SECURITY-1534 tests

---

pom.xml

Additional maintainers will speed the review process and increase the safety of changes.
See [repository permissions updater 1293](https://github.com/jenkins-infra/repository-permissions-updater/pull/1293).

Add two more maintainers

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java

This makes it consistent with `JGitAPIImpl`.

Add missing @Override annotations to CliGitAPIImpl

---

src/main/java/hudson/plugins/git/GitAPI.java
src/main/java/org/jenkinsci/plugins/gitclient/AbstractGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/JGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/RemoteGitImpl.java
src/test/java/hudson/plugins/git/GitExceptionTest.java
src/test/java/org/jenkinsci/plugins/gitclient/CredentialsTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientTest.java
src/test/java/org/jenkinsci/plugins/gitclient/MergeCommandTest.java
src/test/java/org/jenkinsci/plugins/gitclient/PushTest.java

This reduces the amount of deprecated API calls. It doesn't resolve all deprecated warnings.

Reduce deprecated API usage

---

src/test/java/hudson/plugins/git/GitExceptionTest.java
src/test/java/org/jenkinsci/plugins/gitclient/StringSharesPrefix.java

Simplify differences on stable-2.x branch to reduce master branch differences.
Reduce distance to master branch to simplify merge

Reduce differences to master branch

---

pom.xml

It contains new features & a couple of bug fixes:
- https://wiki.eclipse.org/JGit/New_and_Noteworthy/5.6
- https://projects.eclipse.org/projects/technology.jgit/releases/5.6.0

Use JGit 5.6.0

---

pom.xml

Test hung on multi-core machines prior to this change.  Dependency updates also.

Fix multi-core testing, update dependencies

---

src/test/java/org/jenkinsci/plugins/gitclient/GitAPITest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestForCliGit.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestNotIntialized.java

Migrated few of the Tests which are for only CLI Git.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. This is simply a reminder of what we are going to look for before merging your code._
If this is a relatively large or complex change, start the discussion by explaining why you chose the solution you did and what alternatives you considered.

Migrating Tests From JUnit 3 (GitAPITesCase) to JUnit 4 (GitAPITest)

---

src/main/java/org/jenkinsci/plugins/gitclient/cgit/GitCommandsExecutor.java

See https://github.com/jenkinsci/bom/pull/423
and example merged PR in a pipeline component: https://github.com/jenkinsci/workflow-support-plugin/pull/114
cc @MarkEWaite

Make git-client compatible with future guava

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java

- Remove unused imports
- Remove unused acceptSelfSignedCertificates

Remove unused private boolean and imports

---

.github/pull_request_template.md
CHANGELOG.adoc
CONTRIBUTING.adoc
Priorities.adoc
README.adoc
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITest.java

- Use issues.jenkins.io in URLs instead of the outdated issues.jenkins-ci.org
- Remove dead store in a test

Fix issue URLs

---

src/main/java/org/jenkinsci/plugins/gitclient/RemoteGitImpl.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java

Adapts to jenkinsci/jenkins#5467.

Stop using deprecated `Util#join`

---

.github/dependabot.yml

Track GitHub action versions with dependabot

---

.github/labeler.yml
.github/workflows/labeler.yml

Automatically label pull requests containing specific files.

Automate some pull request labeling

---

Jenkinsfile

Need to assess tests when compiled with Java 17.

Test with Java 17 in addition to Java 11 and Java 8

---

src/test/java/jmh/benchmark/FolderForBenchmark.java

This pull request fixes either 1.) Temporary Directory Hijacking Vulnerability, or 2.) Temporary Directory Information Disclosure Vulnerability, which existed in this project.
The system temporary directory is shared between all users on most unix-like systems (not MacOS, or Windows). Thus, code interacting with the system temporary directory must be careful about file interactions in this directory, and must ensure that the correct file permissions are set.
This PR was generated because the following chain of calls was detected in this repository in a way that leaves this project vulnerable.
`File.createTempFile(..)` -> `file.delete()` -> either `file.mkdir()` or `file.mkdirs()`.
This vulnerability can have one of two impacts depending upon which vulnerability it is.
1. Temporary …

[SECURITY] Fix Temporary Directory Information Disclosure Vulnerability in test

---

src/test/java/org/jenkinsci/plugins/gitclient/GitClientMaintenanceTest.java

Maintenance tests were failing on Ubuntu 18, Red Hat Enterprise Linux 7, and Debian 10 in the legacy path.  The legacy path was checking failure modes.
Changes the tests so that all tests check the failure modes.  Reduces the number of tests slightly and reduces the number of assertions per test.
- ~~I have interactively tested my changes~~

Simplify maintenance tests

---

Jenkinsfile

Coverage reported by first build and only Linux

Use JDK 11 for coverage reporting

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/JGitAPIImpl.java
src/test/java/hudson/plugins/git/GitAPIBadInitTest.java
src/test/java/org/jenkinsci/plugins/gitclient/CliGitCommand.java
src/test/java/org/jenkinsci/plugins/gitclient/CredentialsTest.java
src/test/java/org/jenkinsci/plugins/gitclient/FilePermissionsTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPICliGitNotIntializedTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPINotIntializedTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestUpdate.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientCloneTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientMaintenanceTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientTest.java
src/test/java/org/jenkinsci/plugins/gitclient/JGitLightweightTagTest.java
src/test/java/org/jenkinsci/plugins/gitclient/LegacyCompatibleGitAPIImplTest.java
src/test/java/org/jenkinsci/plugins/gitclient/MergeCommandTest.java
src/test/java/org/jenkinsci/plugins/gitclient/NetrcTest.java
src/test/java/org/jenkinsci/plugins/gitclient/PushTest.java
src/test/java/org/jenkinsci/plugins/gitclient/WorkspaceWithRepo.java

See self-review for description of changes.

Miscellaneous low-risk code cleanup

---

pom.xml

Set version to 4.2.0 in preparation for a release that will include JGit 6.5.0.

Prep to release JGit 6.5.0 update

---

.gitattributes

Avoid build failures on some Windows configurations

Declare line termination

---

pom.xml
src/spotbugs/excludesFilter.xml

Avoid introductions of new spotbugs warnings

Increase spotbugs checks

---

CONTRIBUTING.adoc

Automated code formatting is easier to manage and assures consistency
between plugin pull requests.

Add automated formatting note to contributing guide

---

pom.xml
src/spotbugs/excludesFilter.xml

Preparing for future upgrade of the plugin parent pom

Use spotbugs plugin 4.8.2.0 with new exclusions

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java

Username / password authentication sometimes may report a "text file busy" error when cloning a repository.

[JENKINS-72667] Fix "Text file busy" issue with GIT_ASKPASS

---

pom.xml

No commits to the plugin since it was created.
Confirmed plugin compiles.

Remove mramonleon as a plugin maintainer

---

src/main/java/hudson/plugins/git/Branch.java
src/main/java/hudson/plugins/git/GitAPI.java
src/main/java/hudson/plugins/git/GitException.java
src/main/java/hudson/plugins/git/GitLockFailedException.java
src/main/java/hudson/plugins/git/GitObject.java
src/main/java/hudson/plugins/git/GitTool.java
src/main/java/hudson/plugins/git/IndexEntry.java
src/main/java/hudson/plugins/git/Revision.java
src/main/java/hudson/plugins/git/Tag.java
src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/Git.java
src/main/java/org/jenkinsci/plugins/gitclient/JGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/JGitApacheTool.java
src/main/java/org/jenkinsci/plugins/gitclient/JGitTool.java
src/main/java/org/jenkinsci/plugins/gitclient/RemoteGitImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/jgit/SmartCredentialsProvider.java
src/main/java/org/jenkinsci/plugins/gitclient/verifier/NoHostKeyVerifier.java

instanceof pattern matching
Add @Serial annotation
Automated tests pass

Use Java 17 language features

---

CONTRIBUTING.adoc
src/main/java/org/jenkinsci/plugins/gitclient/ChangelogCommand.java
src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/GitClient.java
src/main/java/org/jenkinsci/plugins/gitclient/JGitAPIImpl.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITest.java
src/test/java/org/jenkinsci/plugins/gitclient/JGitAPIImplUnsupportedProtocolTest.java

Backport #1326 and #1327 to the 6.2.x line.

Support command line git 2.51.0
