jenkinsci/git-client-plugin

src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java

Currently (with 1.16.1), when testing git-client-plugin, I am getting
the following error in test_push_tags:
--------------------------------------------------------
The current branch master has no upstream branch.
To push the current branch and set the remote as upstream, use
git push --set-upstream /tmp/hudson4099265862244982437test master
--------------------------------------------------------
The reason that this is happening is that test_push_tags() is using the
PushCommand() pattern, but is failing to specify a refspec.  Also, this
test case is creating a remote url, but is not setting up the master
branch to track that remote url.  So, without a refspec, the behaviour
depends on whether CLI or JGIT is used.
In CLI, it uses whatever push.default specifies.  In my case, it was set …

Fix failure in test_push_tags

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java

I'm also having the errors described in JENKINS-20879 when trying to poll a git repository using a passphrase-protected SSH private key (with the GitCli implementation - as already mentionned in the Jira report, JGit already works fine).  
Looking at the implementation, I understand that the passphrase is provided to git/ssh via a shell script and the `$SSH_ASKPASS` trick.  But according to the ssh manpage, this can only work if `$DISPLAY` is set, because this mechanism is usually dedicated to graphical environments.
SSH_ASKPASS           If ssh needs a passphrase, it will read the passphrase from the current terminal if it was run from a
terminal.  If ssh does not have a terminal associated with it but DISPLAY and SSH_ASKPASS are set, it
will execute the program specified by SSH_ASKPASS …

JENKINS-20879 - make sure $SSH_ASKPASS is not ignored

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/JGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/MergeCommand.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java

<h3>Background</h3>
We are looking to use the Credentials API in our [pretested-integration-plugin](https://wiki.jenkins-ci.org/display/JENKINS/Pretested+Integration+Plugin). However, before we can get started on that, we'll need to add some missing functionalities to the [git-client-plugin](https://github.com/jenkinsci/git-client-plugin). The ability to squash commits when merging being one of them. (Related issue: [JENKINS-28833](https://issues.jenkins-ci.org/browse/JENKINS-28833))
<h3>Implementation</h3>
The implementation was pretty straightforward. `MergeCommand` now requires a `setSquash(boolean squash)` implementation which both `JGitAPIImpl` and `CliGitAPIImpl` received.
<h3>Testing</h3>
Tests were written to test both a squashed and unsquashed merge. We also took it for a spin …

Implemented Squash option on MergeCommand. JENKINS-28833

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java

The CLI implementation of the Git client does not correctly propogate the username for ssh urls and possibly for http(s) urls. To fix this, teach the GIT_SSH scripts for Unix and Windows how to pass the username via "-l" option. In addition, for consistency, include credentials.username with the default user incase http(s) urls don't have user names assigned.
This enables use of a different remote username than the local system username, which seems to be something that was not tested today.
I am not familiar with the test framework used by this plugin, so I wasn't able to figure out how the tests were being run. Ideally we need to provide a test which exhibits this behavior so that we can catch it in the future. Help and insight regarding this would be useful.

JENKINS-29604 - Git CLI client does not propogate username

---

src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java
src/test/java/org/jenkinsci/plugins/gitclient/PushSimpleTest.java
src/test/java/org/jenkinsci/plugins/gitclient/StringSharesPrefix.java

I figured out that we can't do the pushNonFastForward test without first pushing some other commit, so I did some re-work and reworked the pushNoRefspec into pushCurrent and explicitly configured it to push "HEAD" so that we can get the remote ready.
It might be worth re-working how the test is run so that it is not inter-dependent, but I couldn't figure out how to do this.
The new test works with both push.default = simple and push.default = upstream, so I believe this should be correct behavior now.
We do drop testing of "no refspec" but I think that is really a broken test concept anyways unless we're going to find a way to completely 100% clear configuration during tests.
I still have some other errors which I am currently working on determining how to fix, mostly I think related to …

add and fix tests

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/CloneCommand.java
src/main/java/org/jenkinsci/plugins/gitclient/FetchCommand.java
src/main/java/org/jenkinsci/plugins/gitclient/JGitAPIImpl.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java

This is pre-work to make the base git-client plugin able to understand depth for shallow clones. There will be another pull request on the main git-plugin to take it from the UI.

JENKINS-24728  Add ability to specify shallow clone depth

---

CONTRIBUTING.md
pom.xml
src/main/java/org/jenkinsci/plugins/gitclient/CloneCommand.java
src/main/java/org/jenkinsci/plugins/gitclient/FetchCommand.java

@stephenc commented on the power of a good CONTRIBUTING file to guide people as they submit pull requests.  This is my attempt to make some progress toward having a CONTRIBUTING file in the git client plugin which clearly expresses the guidelines for the plugin.
I think guidelines should only be added to the CONTRIBUTING file when the plugin source code actually complies with the guidelines.  Thus, this initial effort states very few guidelines.
I'd like a @reviewbybees to see if others think that is a reasonable approach for the git client plugin

Improve the CONTRIBUTING file and matching code changes

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/JGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/MergeCommand.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java

We are planning to use the Credentials API in our Pretested Integration plugin, but we're lacking certain features in the Git Client plugin. The ability to merge without committing being one of them.
Related issue: [JENKINS-30486](https://issues.jenkins-ci.org/browse/JENKINS-30486)
The MergeCommand interface now requires a setCommit(boolean commit) implementation which both JGitAPIImpl and CliGitAPIImpl received. Commit defaults to true as to not change the plugin's default behaviour.
Two test cases were added to GitAPITestCase to test both a committed and non-commited merge. We also tested our own plugin, using the no-commit option, and all our tests pass as well.

[JENKINS-30486] Added --no-commit option to MergeCommand

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java

Versions of CLI Git < 1.9.0 have limitations when pushing from shallow
clone, which have been lifted in newer versions.
See http://stackoverflow.com/q/6900103 for more details.
After merging this commit GitException will be thrown when trying to
push from a shallow clone with CLI Git < 1.9.0.

JENKINS-31108 Disable push from shallow clone using CGit<1.9.0 

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/GitClient.java
src/main/java/org/jenkinsci/plugins/gitclient/JGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/RebaseCommand.java
src/main/java/org/jenkinsci/plugins/gitclient/RemoteGitImpl.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java

We're replacing all Git CLI calls in our plugin with those of the Git Client, since we'd like to make use of the Credentials API, but it's missing the ability to rebase.
Related issue: [JENKINS-30839](https://issues.jenkins-ci.org/browse/JENKINS-30839)
I added a RebaseCommand and added it to all the GitClient implementations. The implementations are pretty bare-bones and only allow for setting the target.
I added two test cases that test the rebase with and without a conflict. I also tested our own plugin, using a snapshot version of the git client, all the tests pass and the rebase works just fine.

Added RebaseCommand

---

pom.xml
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java

Including one more JGit jar from the JGit 3.7.1 package allows JGit to support symbolic links in some cases.
Users running Java 6 will not have symlink support because the JGit library won't be loaded.
Users running Windows with default settings will not have symlink support because Windows does not allow symbolic links by default.
Users running Linux or FreeBSD or HP-UX or AIX or other Unix-like environments should have symbolic link support so long as they are running Java 7 or newer.

Fix JENKINS-30371 allow symlinks with jgit

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java

`git-client-plugin` calls `echo` with an absolute path from `/bin/echo` on *-nix operating systems which causes an error on any system where `echo` may not be located there for whatever reason.
I am running jenkins on [NixOS](http://nixos.org) which does not adhere to [FHS](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard) meaning `echo` is not located in `/bin/echo`. 
This PR changes the code such that echo is always called without absolute path so it is executed from `$PATH`.
I can't think of any good reason why executing it from an absolute path should be favourable and with this change it will work fine if `echo` is located elsewhere.
This fixes [JENKINS-36255](https://issues.jenkins-ci.org/browse/JENKINS-36255)

do not call echo from absolute path

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java

Noticed while testing https://github.com/jenkinsci/github-branch-source-plugin/pull/60.
```
hudson.plugins.git.GitException: Could not merge AnyObjectId[99608938c2e9f12e73c4aba94b81a4dbdaffb937]
at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$3.execute(CliGitAPIImpl.java:590)
at org.jenkinsci.plugins.github_branch_source.GitHubSCMSource$MergeWith.decorateRevisionToBuild(GitHubSCMSource.java:664)
at hudson.plugins.git.GitSCM.determineRevisionToBuild(GitSCM.java:991)
at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1080)
at …
Caused by: hudson.plugins.git.GitException: Command "git merge 99608938c2e9f12e73c4aba94b81a4dbdaffb937" returned status code 1:
stdout: Auto-merging Jenkinsfile
CONFLICT (content): Merge conflict in Jenkinsfile
Automatic merge failed; fix conflicts and then commit …
```

The original GitException from a failed merge was good enough, no need to rethrow it

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java

Avoid string index out of bounds exception on unexpected output from
"git branch -v --no-abbrev" (as reported in JENKINS-34309).
The JENKINS-34309 issue may be related to gitlab bug 14453
https://gitlab.com/gitlab-org/gitlab-ce/issues/14453
Added a test to check that empty repo reports no branches.  Empty
repo does not show the problem which was detected in JENKINS-34309.
My attempts to duplicate JENKINS-34309 in an automated test have all
failed.  Those attempts are included in this commit (though unsuccessful
at duplicating the problem).

[JENKINS-34309] Only parse reasonable branch line output

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java

**Expectation**: When I set the checkout timeout, I'm expecting that Jenkins uses it when it comes to checkout a commit.
**Problem**: However, it appears that when you select the "Check out to a specific local branch", the first checkout command does not set correctly the timeout.
**Why it's a problem**: I'm using git lfs, and git lfs files are downloaded during the checkout option. For other reasons I can't use the git lfs pull command. 
**How to reproduce it**: 
1. Use any version of git-plugin and git-client-plugin. 
2. Create a freestyle project, add the following parameters: 
1. Timeout=120 for the Advanced checkout option
2. ** for the Checkout to a specific local branch. 
3. Build the project.
The first checkout will be displayed with a timeout of 10 instead of 120.
**Before**:
``` …
```

[JENKINS-37185] Honor checkout timeout

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/JGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/SubmoduleUpdateCommand.java
src/test/java/org/jenkinsci/plugins/gitclient/CredentialsTest.java

Teach the submoduleUpdate call to perform submodule URL lookup, and call
"submodule update" separately for each submodule. Lookup the
credentials, and call it using launchCommandWithCredentials. This
enables submodules to correctly get the SSH or HTTP setup necessary such
that the Jenkins credentials will be passed into each submodule.
We can't just call "git submodule update" since it may be possible
(however unlikely!) that each submodule wants to use a separate
credential. Thus, perform lookup using each URL and run through a
forloop to actually update each submodule instead of depending on the
git implementation to do this for us.
JENKINS-20941 - Credentials and Submodules
NOTE: this depends on a change in the git-plugin to enable setting up default credentials or adding credentials …

(WIP) git-client: teach submoduleUpdate how to pass credentials

---

Jenkinsfile

There are some issues on ci.jenkins.io with GIT_COMMITTER_NAME and
GIT_COMMITTER_EMAIL not getting set properly, but the "java" agents
either have properly configured ~/.gitconfig files or git is
autodetermining the email somehow. In any case, this should be better
in general.
cc @rtyler

Use java agent on ci.jenkins.io

---

.gitmodules

The Jenkins git-client plugin currently checks out submodules by initializing them into PATH, where PATH is erroneously specified as the *name* of the submodule. In many repositories, the submodule name and path match, but this is not a git requirement. When they do not match, this results in an error condition. [JENKINS-37495](https://issues.jenkins-ci.org/browse/JENKINS-37495)
I added a new submodule named [`puppetssh`](https://github.com/puppetlabs/puppetlabs-sshkeys.git) that uses the path `modules/sshkeys`. Since these mismatch, they will trigger the bug in the old `master`.
See pull request #225

Added puppetlabs-sshkeys repository as a submodule named 'sshkeys'

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java

The Jenkins git-client plugin currently checks out submodules by initializing them into PATH, where PATH is erroneously specified as the *name* of the submodule. In many repositories, the submodule name and path match, but this is not a git requirement. When they do not match, this results in an error condition. [JENKINS-37495](https://issues.jenkins-ci.org/browse/JENKINS-37495)
I added a new method named `getSubmodulePath()`, which takes the name of the submodule and fetches the `path` as defined in `.gitmodules`. I updated the existing submodule update code to call this method and get the path explicitly, rather than reusing the *name* of the submodule, which was mislabeled as `sUrl`. The old `sUrl` was renamed `sModuleName` to reflect its true nature.
Automated testing isn't going to …

Correctly handle submodules whose name and path do not match

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java

The Jenkins git client currently determines the list of submodules by reading `.git/config`. Unfortunately, this file may contain references and URLs for any submodules that have been accessed in the working directory of this repository, not simply the ones that exist in the active branch. In many cases this will result in Jenkins attempting to clone non-existent submodules and fail. [JENKINS-37419](https://issues.jenkins-ci.org/browse/JENKINS-37419)
I explicitly instruct git to read the `.gitmodules` file when gathering its list of submodules to update. By iterating through `.gitmodules`, this ensures that only submodules for *this* branch are synchronized and updated. The regex string used is the same as the one a few lines later. Along with #225, this should fix some issues related to …

Reference the .gitmodules file to get a list of current submodules

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java

This was a blocking issue for us, so I went ahead and implemented the simplest fix. 
Related JIRA issue: https://issues.jenkins-ci.org/browse/JENKINS-40166
I looked into adding UnitTests for quoting, but it didn't seem straightforward and it's platform dependent.

Properly escape special Windows Batch characters

---

src/main/java/org/jenkinsci/plugins/gitclient/RemoteGitImpl.java

[JENKINS-37899](https://issues.jenkins-ci.org/browse/JENKINS-37899) RemoteGitImpl: Take a snapshot of the credentials before passing them to the git client proxy.
We need to snapshot of the credentials before passing them to the git client proxy so that the credentials are snapshotted before being serialized and transferred to the build agent through Jenkins remoting.

[JENKINS-37899] RemoteGitImpl: Take a snapshot of the credentials before passing them to the git client proxy

---

src/main/java/org/jenkinsci/plugins/gitclient/CheckoutCommand.java
src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/JGitAPIImpl.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientTest.java

This is a refactoring of @matthauck's changes from jenkinsci/git-client-plugin#206.  I could not get his changes to work because `git lfs fetch` was failing with this error: can't resolve ref: "HEAD" (See https://github.com/jenkinsci/git-plugin/pull/414#issuecomment-260159466).  After reading git-lfs/git-lfs#1307, I realized that `git lfs fetch` requires the code to be checked out before it can know which large files to download.  The original code was attempting to run `git lfs fetch` after `git fetch` but before `git checkout`, which wasn't working because there wasn't a local `HEAD` yet.  This means the changes proposed by @estyrke in https://github.com/jenkinsci/git-plugin/pull/414#issuecomment-263843310 also won't work.  The fix was to remove the call to `git lfs fetch` and add a …

[JENKINS-35687] Add simple git lfs support

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/GitClient.java
src/main/java/org/jenkinsci/plugins/gitclient/JGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/RemoteGitImpl.java
src/test/java/org/jenkinsci/plugins/gitclient/CliGitAPIImplTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java
src/test/java/org/jenkinsci/plugins/gitclient/JGitAPIImplTest.java
src/test/java/org/jenkinsci/plugins/gitclient/JGitApacheAPIImplTest.java

- Sadly JGit needs to try and guess
@reviewbybees
(Downstream PR for git-plugin to use the API will follow - based on WIP in https://github.com/jenkinsci/git-plugin/tree/jenkins-40834 that needed this change to have a hope of working)

[JENKINS-40834] Add an API to resolve symbolic refs

---

src/main/java/org/jenkinsci/plugins/gitclient/JGitAPIImpl.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientTest.java

cf.
https://issues.jenkins-ci.org/browse/JENKINS-43198
https://bugs.eclipse.org/bugs/show_bug.cgi?id=514434

JENKINS-43198: Workaround a jgit bug on cleaning directories mentionned in .gitignore

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/test/java/org/jenkinsci/plugins/gitclient/CliGitAPITempFileTest.java
src/test/java/org/jenkinsci/plugins/gitclient/CredentialsTest.java

The security fixes in git client plugin 2.4.4 shifted from preferring the system temporary directory (with default permissions on the files) to preferring a temporary directory adjacent to the workspace directory.  That change exposed the git client plugin credentials code (command line git, with all its complications) to the path name of the workspace, where previously the credentials code only used the path name to the system temporary directory.
This fixes the following bugs:
* [JENKINS-44041](https://issues.jenkins-ci.org/browse/JENKINS-44041) - Windows authenticated git checkout fails if '(' or ')' in path to workspace
* [JENKINS-43931](https://issues.jenkins-ci.org/browse/JENKINS-43931) - Windows authenticated git checkout fails if ' ' in path to workspace
* …

Fix workspace path regressions

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java

Following [JENKINS-20879] and [JENKINS-25194], I needed setsid support to use a git ssh passworded key on a Mac OSX node. This PR adds /usr/local/bin and /usr/local/sbin to the search path for the setsid binary. 
Problem is OSX does not have the setsid command by default. On recent versions of OSX you can't modify system directories like /usr/bin or /bin, even as root (due to SIP/rootless). Even after finding setsid for OSX and compiling it, git-client-plugin won't find the command because it could only go in /usr/local/bin. 
For anyone here from google, this is the basic setsid I used that saved me some time:
https://github.com/jerrykuch/ersatz-setsid

expand setsid path detection to /usr/local

---

Jenkinsfile

Long term support release 2.60.1 arrived today.  Ready for use, ready to test.

Use LTS 2.60.1 for plugin compat tests

---

src/test/java/org/jenkinsci/plugins/gitclient/GitClientTest.java
src/test/java/org/jenkinsci/plugins/gitclient/LegacyCompatibleGitAPIImplTest.java

Many continuous integration jobs will default to cloning a subset of the
remote repository because it reduces disc use and clone time and network
traffic.  This change allows the tests to run successfully even if they
are started from a shallow clone and which includes no tags.

Do not assume that local repository is a full clone

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/JGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/MergeCommand.java
src/test/java/org/jenkinsci/plugins/gitclient/MergeCommandTest.java

Hi,
as far as I know the current implementation of merge command does not support the parameter strategy-option for recursive merge strategy. I need to use recursive merge with the option theirs. Because JGit does not support the full set of features I implemented this feature as simple strategy RECURSIVE_THEIRS to support CLI and JGit implementation.  
Regards
Martin

Implement RECURSIVE_THEIRS merge strategy option

---

src/main/java/org/jenkinsci/plugins/gitclient/GitURIRequirementsBuilder.java
src/test/java/org/jenkinsci/plugins/gitclient/GitURIRequirementsBuilderTest.java

Tests scp URL form in GitURIRequirementsBuilderTest
Adds assertions for path.getPath(), including incorrect relative scp path.
Credentials PathRequirement incorrectly converts relative path to
absolute path.  Adapt the test to that error, since PathRequirement
is likely used in many other cases where the prefixing of a '/' to the
relative path is the expected and desired behavior.
Passed my interactive testing, and automated tests on multiple platforms.
Replaces #242

JENKINS-43022 - Honor git credential path exclusion and inclusion

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java

The current implementation of getRepository() fails to work if the
repository directory in question has a .git file (known as a symref)
which points to the real directory. This causes problems if you try to
directly open a submodule or worktree repository using the git client.
This happens because FileRepositoryBuilder.create() uses .setGitDir() to
set the git directory which expects only a proper git directory path.
Instead, set the worktree and have the RepositoryBuilder figure out
where the git directory is.
This implementation is identical to the JGit implementation, which is
a nice bonus.
Add additional tests for both CliGit and JGit which verify that a git
client can open a repository object properly for repositories
with .git symrefs.
Without this fix, the git plugin will fail to …

[JENKINS-45729] fix getRepository() to work with symref git files

---

pom.xml
src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/CloneCommand.java
src/main/java/org/jenkinsci/plugins/gitclient/FetchCommand.java
src/main/java/org/jenkinsci/plugins/gitclient/JGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/PushCommand.java
src/main/java/org/jenkinsci/plugins/gitclient/RevListCommand.java

Precursor to [JENKINS-45771](https://issues.jenkins-ci.org/browse/JENKINS-45771), we need the ability
to turn off shallow if another extension has turned it on.
@reviewbybees

[JENKINS-45771] Ensure all command boolean options can be toggled, not just set once

---

src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java

The previous test started failing when I submitted a pull request
from a branch that contained the letters "od".  That's too common
a character sequence to fail a test.
Ultimately this needs a better way of testing than using a local
mirror.  The local mirror creates a useful and interesting history,
but the same types of useful and interesting history could be
placed into a sample repository, or could be created by the test,
without the ongoing risk of a newly created branch causing a test
failure due to pattern matching.

Narrow branch name matching test for fewer collisions

---

pom.xml

Fix exception handling for opening bitmap index files.
Unlikely to be detected in common Jenkins usage, but better to run the
current released version for those cases where it might be found.
See https://projects.eclipse.org/projects/technology.jgit/releases/4.5.3
@reviewbybees

Use jgit 4.5.3

---

pom.xml
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java

Use the maven `enable-jacoco` profile as provided by the parent pom.  Since the parent pom already provides code coverage settings, there is no reason to duplicate those settings in the plugin
@reviewbybees

Code coverage from parent pom

---

pom.xml

I found that `workflow-job`, with a `test`-scoped dep on `git`, had `requireUpperBoundDeps` violations whereby `git-client` was asking for a newer version of `commons-codec` than `jenkins-core` actually bundled.
Since the dep was `provided`, it was not being bundled in `git-client.hpi` anyway (and even if it were, without `pluginFirstClassLoader` it would be ignored).
@reviewbybees

commons-codec is provided by jenkins-core

---

pom.xml

JENKINS-39832 may be visible again due to the update to JGit 4.5.3.
This revert is a test which will be used in the staging environment
to confirm (or refute) that the change from JGit 4.5.2 to JGit 4.5.3
introduces "missing object exception" reports.
This reverts commit 4de8bb5a5e77e94e422828798d0bbb218a7840cc.

Revert "Use jgit 4.5.3" - test JENKINS-39832

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/JGitAPIImpl.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientTest.java

[JENKINS-39832](https://issues.jenkins-ci.org/browse/JENKINS-39832), [JENKINS-46639](https://issues.jenkins-ci.org/browse/JENKINS-46639), [JENKINS-46628](https://issues.jenkins-ci.org/browse/JENKINS-46628), and [JENKINS-44323](https://issues.jenkins-ci.org/browse/JENKINS-44323) all report variations of a "missing object exception".
One possible cause of a missing object exception is looking for a commit in a repository which does not include that commit.  The exception message now includes the SHA1 that is being sought, and the path to the workspace being searched.
@reviewbybees

Add missing object exception details

---

src/main/java/org/jenkinsci/plugins/gitclient/JGitAPIImpl.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientTest.java

Previously the changelog through a different exception in JGit than in CliGit.  This includes a test for that exception, and makes JGit match CliGit.

Assert exception if no changelog destination specified

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/test/java/org/jenkinsci/plugins/gitclient/CliGitAPIImplTest.java

If `git branch -v --no-abbrev` output contains a line like " very-long-string-with-more-than-44-characters\n", it will bypass the first `if` condition of the `while` block and will end up being split. However, since it will only contain 1 token (as there are no spaces after applying `substring(2)`), accessing `branchVerboseOutput[1]` results in ArrayIndexOutOfBoundsException. This fix is to avoid such exception and pre-validate the array size (should be greater than 1 in order to contain, at least, the branch name and the SHA1).

Protect against ArrayIndexOutOfBoundsException (related to JENKINS-34309)

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/JGitAPIImpl.java
src/test/java/org/jenkinsci/plugins/gitclient/CredentialsTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java

Add a test for reference repo path, and use a reference repo in the credentials tests for both CliGit and JGit.
Switch the credentials test to use CloneCommand rather than FetchCommand, since CloneCommand is the more commonly used and provides reference repository support which FetchCommand does not directly support reference repositories.

Log reference repo path improvements

---

src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java

[JENKINS-47373](https://issues.jenkins-ci.org/browse/JENKINS-47373)
If tests are executed without setting local/global git configuration (i.e. neither .git/config either ~/.gitconfig correctly set), tests in class org.jenkinsci.plugins.gitclient.JGitApacheAPIImplTest fail. That configuration should be set before executing the test. (See JIRA for more details)
@reviewbybees specially @MarkEWaite

[JENKINS-47373] Set git configuration to avoid test failures.

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/test/java/org/jenkinsci/plugins/gitclient/CredentialsTest.java

Set `GIT_TERMINAL_PROMPT=0` for git versions 2.3 and later to prevent git credential prompting.
Set `GCM_INTERACTIVE=never` for Windows git versions 2.9 and later to prevent Git Credential Manager for Windows from prompting.
Configure Windows repositories for no credential helper when creating the repository.
Test credentials with `ls-remote` rather than using a full clone.  More reliable.

[JENKINS-35959] Don't prompt for credentials

---

pom.xml

Just a follow-up to the issues like [JENKINS-47645](https://issues.jenkins-ci.org/browse/JENKINS-47645). We offer plugins for HttpClient and JSch, so it does not make much sense to bundle libraries and be at risk of classloading conflicts.
@MarkEWaite @reviewbybees

Update plugin to use Apache Http Client API and JSch plugins

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/JGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/RevListCommand.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientTest.java

When implementing isCommitInRepo() for the CLI git implementation we use
git rev-list, assuming that if this command fails then the commit
doesn't exist in the repository. This is technically correct.
However, git rev-list actually performs a complete revision walk, which
for large repositories can take a long time. For example, on the Linux
repository, git rev-list HEAD took around 30 seconds. This is entirely
due to the command producing an entire list of all revisions leading
back to the beginning of history.
But isCommitInRepo() doesn't even care about that! We can significantly
reduce the cost of this function in a number of ways. One, we could
re-implement this using various other git commands, such as git
cat-file. Or, we could ask rev-list not to actually walk the revisions.
This …

use --no-walk when merely checking if a revision exists

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientTest.java

[JENKINS-30589](https://issues.jenkins-ci.org/browse/JENKINS-30589) reports that the CliGitAPIImpl.getRemoteReferences throws a GitException if there are no matching remote references when the documentation says it should return an empty Map.
The first commit shows the failure in CliGitAPIImpl, and confirms that JGitAPIImpl behaves correctly (as defined in the javadoc for the GitClient.getRemoteReferences method).
The second commit fixes the CliGitAPIImpl implementation to not throw the exception.
The exception was originally placed in CliGitAPIImpl to diagnose unexpected content in the output of `git ls-remote`.  I believe there were cases when a line break control character was being returned in the output and that was causing the simple line break based parsing to fail.  Now, instead …

[JENKINS-30589] Get remote references consistent return in all implementations

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientTest.java
src/test/java/org/jenkinsci/plugins/gitclient/SubmodulePatternStringTest.java

[JENKINS-46054](https://issues.jenkins-ci.org/browse/JENKINS-46054) reports that submodules whose URL includes the text `.url` cannot be cloned or updated into a Jenkins workspace.
The `git config` output parsing regular expression incorrectly extended across a space character when a space character is not valid in the name of a git remote.
This pair of changes writes tests for the problem and fixes the problem.

Fix submodule url regex [JENKINS-46054]

---

pom.xml
src/main/java/hudson/plugins/git/Branch.java
src/main/java/hudson/plugins/git/GitObject.java
src/main/java/hudson/plugins/git/Tag.java
src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/GitClient.java
src/main/java/org/jenkinsci/plugins/gitclient/JGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/RemoteGitImpl.java
src/test/java/hudson/plugins/git/BranchTest.java
src/test/java/hudson/plugins/git/GitObjectTest.java
src/test/java/hudson/plugins/git/TagTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientTest.java

[JENKINS-45447](https://issues.jenkins-ci.org/browse/JENKINS-45447) reports that checkout of a freestyle  job with a wildcard in the branch name (and many other cases which invoke a more advanced branch selection mechanism) with many tags in the repository is dramatically slower than earlier releases.
[31fedce9c](https://github.com/jenkinsci/git-plugin/commit/31fedce9c41c9006c886835e03c9fe825d49aba6) commit added tag checks to the evaluation loop for branch names.  Unfortunately, tag evaluation needs both the tag name and the SHA1 of the commit identified by the tag.  The implementation used revParse() to compute that SHA1.  With many tags in the repository (bug report example was 60,000 tags), the checkout time was significant.
I found that even the number of tags in the git plugin …

[JENKINS-45447] Add GitClient.getTags()

---

src/main/resources/META-INF/hudson.remoting.ClassFilter

https://github.com/jenkinsci/jenkins/pull/3120 shows that this plugin (well, really `git`) does unusual stuff that required custom whitelist entries.
@reviewbybees

Custom ClassFilter entries

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java

Setting GIT_SSH_VARIANT=ssh to environment, solves [JENKINS-49111]

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientTest.java
src/test/java/org/jenkinsci/plugins/gitclient/SubmodulePatternStringTest.java

The initial fix for [JENKINS-46054](https://issues.jenkins-ci.org/browse/JENKINS-46054) - update fails if submodule remote name ends with '.url'. introduced [JENKINS-48818](https://issues.jenkins-ci.org/browse/JENKINS-48818), a more serious regression than the bug it fixed.  Submodule update now fails with remote names which contain a whitespace character.  In git client 3.6.4 and prior, submodule update worked, even with a remote name which contained a space character.
This change adds more tests and resolves the regression introduced in git client 3.7.0.  It was verified interactively with the [JENKINS-48818 test job](https://github.com/MarkEWaite/jenkins-bugs/blob/JENKINS-48818/Jenkinsfile) and the [JENKINS-46054 test job](https://github.com/MarkEWaite/jenkins-bugs/blob/JENKINS-46054/Je …

Fix JENKINS-48818 and keep JENKINS-46054 fixed

---

src/main/java/org/jenkinsci/plugins/gitclient/AbstractGitAPIImpl.java

Investigating one another `java.lang.NoClassDefFoundError: Could not initialize class jenkins.model.Jenkins$MasterComputer` exceptions, I come across we do not have to load the class at all - if fact https://github.com/jenkinsci/jenkins/commit/0b27f364f99ec98cb616d4f0cfc0858ecf339852 discourage users from doing so.

Avoid refering to now deprecated MasterComputer.localChannel to avoid loading classes over remoting

---

src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java

Command line git 2.17.0 changed the case of a word in a message and
caused tests to fail.  Case insensitive comparisons are good enough for
these tests.
Also replaced several duplicated locations with a method that is easier
to read and produces a better diagnostic on failure.

Ignore case in git exception message substring asserts

---

src/main/java/org/jenkinsci/plugins/gitclient/JGitAPIImpl.java

Christian Halstrick of the JGit project sat with me for a day at the Jenkins Hackfest after FOSDEM.  We reviewed the JGit implementation and made improvements while capturing action items.
@reviewbybees

JGit improvements from Christian Halstrick review

---

src/test/java/org/jenkinsci/plugins/gitclient/CredentialsTest.java

JGit 4.5 handles absence of username from the ssh URL differently than
JGit 4.11.
The ssh URL github.com:MarkEWaite/tasks.git with the username argument
"git" is handled correctly by JGit 4.11 and incorrectly by JGit 4.5.
JGit 4.5 handles conflicts between the username embedded in the ssh
URL and the username argument differently than JGit 4.11.
The ssh URL git@github.com:MarkEWaite/tasks.git with the username
argument "jenkins" is handled correctly by JGit 4.11 and incorrectly
by JGit 4.5.
JGit 4.5 honors the username argument instead of the username embedded
in the ssh URL.
JGit 4.11 honors the username embedded in the ssh URL instead of the
username argument.
Secure shell versions prior to OpenSSH 7.7 honored the username
embedded in the ssh URL instead of the username argument.  That …

Narrow jgit exclusion in credentials test

---

README.md

Note in the README that incrementals support needs maven 3.5.0 or later.
Also renames title of the link to the documentation page.  The Jenkins plugins site is not a wiki.

Maven 3.5.0 or later is required

---

src/main/java/org/jenkinsci/plugins/gitclient/Git.java
src/main/java/org/jenkinsci/plugins/gitclient/RemoteGitImpl.java

org.jenkinsci.remoting.util.AnonymousClassWarnings warn:
WARNING: Attempt to (de-)serialize anonymous class org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1
WARNING: Attempt to (de-)serialize anonymous class org.jenkinsci.plugins.gitclient.Git$1
see: https://jenkins.io/redirect/serialization-of-anonymous-classes/
https://issues.jenkins-ci.org/browse/JENKINS-50457

Convert anonymous MasterToSlaveFileCallable to member

---

CONTRIBUTING.md

The Cloudbees Jenkins is not used anymore.

Update Jenkins job link in CONTRIBUTING documentation

---

src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java

Otherwise they would fail if fetch.prune = true on system or global level.

Decouple git fetch tests more from execution environment

---

src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java

When `LANG=C mvn -Dtest=CliGitAPIImplTest#test_clean test` fails, give a better message than the exception from "git add".
This is not foolproof, just an aid for diagnosing test failures when the locale is unable to support the filename in the test.
@darxriggs since you've been looking at tests recently on the plugin, I'd love to have you review this pull request.

Report better exception if filename not supported

---

src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java

The earlier assertNotEquals was not as strong as a specific assertion that in the case of command line git, it is expected that an annotated tag will not be found (and will thus return null).  It is a strange condition that getHeadRev for an annotated tag returns null from command line git and returns non-null from JGit, but that is the reality.
@darxriggs since you've been looking at tests recently on the plugin, I'd love to have you review this pull request.
Found this while exploring test failures on a specific Ubuntu 16 machine when those same failures do not happen on any of my other Ubuntu 16 machines.

Assert annotated tag is null

---

src/test/java/org/jenkinsci/plugins/gitclient/CredentialsTest.java

Prevent credentials test failures due to 2 minutes of credentials test execution.  Limit test to 1 minute.

Stable 2.7 reduce credentials test verbosity

---

src/test/java/org/jenkinsci/plugins/gitclient/CredentialsTest.java

Reduce credentials test verbosity to reduce spurious CI test failures due to 2 minutes of testing.  Reduce to 1 minute of testing.

Reduce credentials test verbosity

---

pom.xml

It seems httpcore slipped into the plugin, since `org.eclipse.jgit.http.apache` has a direct dependency on it. This excludes it again.

Exclude httpcore, since it's already in the httpcomponents API plugin

---

src/test/java/hudson/plugins/git/GitToolResolverTest.java
src/test/java/hudson/plugins/git/GitToolTest.java

Just an extra test, which verifies that Core Tool management logic is fine for Jenkins master node. 
https://github.com/jenkinsci/git-plugin/pull/605 is a related fix in the downstream plugin
@MarkEWaite @btk3000 @jenkinsci/code-reviewers

Add test that verifies invocation of ToolInstallers on master

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/CloneCommand.java
src/main/java/org/jenkinsci/plugins/gitclient/JGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/SubmoduleUpdateCommand.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java

This implements https://issues.jenkins-ci.org/browse/JENKINS-21248.
The original implementation is by @fujii - see pull request #303.
I rebased his commit 89ba2d3ff38ec5bc870441ec06b73fbfcab6743e on master (without changes) and added improvements via new commits.
The tests are working fine now with a locally created git repository containing a submodule.

shallow submodule update

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/JGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/SubmoduleUpdateCommand.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java

This change uses an ExecutorService to optionally update submodules in
parallel. This can dramatically improving update times for
repositories with lots of submodules. Since the CliGitAPIImpl class
doesn't launch a single "git submodule update" command, but instead
launches one command per submodule, we can't use the "--jobs" CLI
argument for git, available since git 2.9.0.

[JENKINS-44720] Add option for updating submodules in parallel

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java

[JENKINS-52891](https://issues.jenkins-ci.org/browse/JENKINS-52891)
A timeout is always used for a cli git command and therefore should always be logged.
Options a timeout may be set
- timeout parameter for some commands
- system property org.jenkinsci.plugins.gitclient.Git.timeOut
- default of 10 minutes
So far the timeout was only logged for commands where
a) it cannot be customized
b) it can and actually was customized
Category a) some commands with correct default timeout logging so far
> git --version # timeout=10
> git init ... # timeout=10
> git config ... # timeout=10
> git submodule init # timeout=10
Category b) commands with missing default timeout logging so far
> git fetch ...
> git checkout ...
> git submodule update ...

[JENKINS-52891] Always log the timeout for a CliGit command

---

src/main/java/hudson/plugins/git/Revision.java
src/test/java/hudson/plugins/git/RevisionTest.java

implementation
* no Guava required
* use Java 8 features for improved clarity
* fix wrong Javadoc
* remove non-required {@inheritDoc}
tests
* reduce variable scope
* follow naming conventions
* fix parameter order when using assertEquals(expected, actual)
* remove unused variables
* misc minor improvements

Improve Revision implementation and tests

---

src/main/java/org/jenkinsci/plugins/gitclient/AbstractGitAPIImpl.java

This fixes an issue reporting missing ServletException on agent side, as
MasterComputer is pulling it, but FilePath isn't.

[JENKINS-53279] Remove deprecated reference

---

pom.xml
src/main/java/org/jenkinsci/plugins/gitclient/JGitAPIImpl.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java

JGit 5.0.2 fixes the behavior of prune during fetch so that the alternative implementation is no longer required.  Unfortunately, JGit 5 also logs warnings that were not logged previously when it attempts to remove a directory that is not empty.
@darxriggs I'd love to have your review of the proposed change.

Use JGit's implementation of prune during fetch

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/test/java/org/jenkinsci/plugins/gitclient/CliGitAPIWindowsFilePermissionsTest.java

See [JENKINS-53933](https://issues.jenkins-ci.org/browse/JENKINS-53933)
~Please say if I messed up the import statements~ I did 🤭
Yay for tests! 🙌
Hopefully we can get this in before 4.0 release!
We have had success with this and using OpenSSH from Microsoft 😎

[JENKINS-53933] set file permissions to allow use of openssh on windows

---

Jenkinsfile
pom.xml
src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/JGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/Netrc.java

Jenkins 2.121.3 is the most recent 2.121 release.
The Jenkins 2.138.1 release introduces a new requirement for instance-identity that needs more analysis before testing with 2.138.1
Jenkins 2.107 is a year newer than Jenkins 2.60.3 and is already superseded by two LTS releases.

Depend on Jenkins 2.107.3 and test 2.121.3

---

src/test/java/org/jenkinsci/plugins/gitclient/CredentialsTest.java

I have a large collection of authentication data In my private test environment that I use to test the git client plugin authentication on multiple platforms and with both git implementations.  
The prior implementation tried to maximize the number of tests executed within the time limit by using a `ClassRule` based JenkinsRule.  The tests run correctly with the ClassRule, but the Jenkins based reporting of the results causes a spurious error.
Rather than attempt to resolve the spurious error, it is simpler to use a `Rule` instead of a `ClassRule`.  The `Rule` creates a JenkinsRule for every test case.  That is less efficient at runtime but gives the desired results in test reporting.

Stable 2.7 fix credentials test reporting failure

---

pom.xml
src/test/java/org/jenkinsci/plugins/gitclient/GitClientTest.java

Specific assertions for changelog content based on past behavior

Add another JENKINS-29977 test

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientTest.java

Place the test in the GitClientTest parameterized test class so that it will be tested on all three implementations and will test with the intentionally randomized fetch parameters.

[JENKINS-55284] Force update existing tags

---

pom.xml

Includes security fixes which should be irrelevant to the Jenkins use case.  Fixes are included just in case there is a surprise and they are relevant to the Jenkins use case.
See the [mailing list announcement](https://www.eclipse.org/lists/jgit-dev/msg03749.html) and the [release notes](https://projects.eclipse.org/projects/technology.jgit/releases/4.5.5) for more information.

Use JGit 4.5.5

---

pom.xml
src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/JGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/SubmoduleUpdateCommand.java
src/main/java/org/jenkinsci/plugins/gitclient/cgit/GitCommandsExecutor.java
src/main/java/org/jenkinsci/plugins/gitclient/cgit/package-info.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java
src/test/java/org/jenkinsci/plugins/gitclient/cgit/GitCommandsExecutorTest.java

This PR fixes an error introduced in https://github.com/jenkinsci/git-client-plugin/pull/348 where exceptions arising in git submodule update commands would be mistakenly suppressed. A test case has been added to verify the new behavior is correct.
Also, another fix is included which provides proper names to the threads in the `ExecutorService` pool via the `NamingThreadFactory` class.

Check for exceptions when updating submodules

---

Jenkinsfile
pom.xml

Test with the latest Jenkins LTS release, Jenkins 2.150.2.
Update the version number in the pom file for a future release

Require Jenkins 2.107

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/test/java/org/jenkinsci/plugins/gitclient/CliGitAPIWindowsFilePermissionsTest.java

We saw some issues when jenkins agents where running in windows docker containers and docker host was connected to an active directory
This works since the owner is correct because the process owner is the one who created the file.

use current owner to avoid user lookup

---

src/test/java/org/jenkinsci/plugins/gitclient/CredentialsTest.java

The junit test reporter plugin that reports test results during test execution will incorrectly report a test failure if the unit test XML file is kept open with incomplete content.  The credentials test leaves the content open for the duration of the test and that frequently fails due to the incomplete content in the open file.

Avoid test fails: 50 sec limit on credentials test

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java

Fix [JENKINS-56116](https://issues.jenkins-ci.org/browse/JENKINS-56116) - Use raw format on ancient git
Specific format characters like '%B' are not supported on old git versions like git 1.7.1 as included with CentOS 6.
Command line git 1.7.1 lacks several capabilities and is not officially supported by the Jenkins git plugin.  However, some use cases work with CentOS 6.  There is no need to break existing users for this specific case, since it is easy enough to use the old 'raw' format as was done in long ago versions of the git plugin.

JENKINS-56116 - Adapt to ancient git versions

---

pom.xml
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java
src/test/java/org/jenkinsci/plugins/gitclient/SubmodulePatternStringTest.java

Update to the most recent plugin parent pom so that the latest parent pom improvements are available to the plugin.  That includes automatic creation of temporary directories with a space in the directory path.
Three tests needed adaptation for spaces in temporary directory paths due to [JENKINS-56175](https://issues.jenkins-ci.org/browse/JENKINS-56175), "Submodule with space in git URL won't update".  The tests avoid the bug rather than fixing the bug.  
My initial attempts to fix [JENKINS-56175](https://issues.jenkins-ci.org/browse/JENKINS-56175) failed during integration testing.  I don't want to spend time fixing that corner case when there are many much broader cases that need attention before the release of git client plugin 3.0.0 and git plugin 4.0.0.

Use parent pom 3.37

---

CONTRIBUTING.md
Jenkinsfile
pom.xml
src/main/java/org/jenkinsci/plugins/gitclient/JGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/LegacyCompatibleGitAPIImpl.java

Includes changes to:
* Compile and test with Java 11 in addition to testing with Java 8
* Require Jenkins 2.121 as minimum version to match the git plugin change for Java 11 compile and test
* Use spotbugs instead of findbugs for static analysis
* Use JGit 5.3.0
* Use parent pom 3.40
* Use latest maven javadoc plugin release (for Java 11 compatibility)

Use JGit 5.3 and parent pom 3.40

---

pom.xml
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java

Several bug fixes from 5.3.0, including:
* 545162 Fix diff when deleted submodule is replaced by normal files
* 545920 Apache MINA sshd: fix cloning of large repositories
* ObjectUploadListener: Add callback interface which is invoked after object upload was completed.
* Fix GC to delete empty fanout directories after repacking
* 546190 Fix pack files scan when filesnapshot isn't modified
* Remember the cause for invalidating a packfile

Use JGit 5.3.1

---

pom.xml
src/test/java/org/jenkinsci/plugins/gitclient/PushTest.java

Update to JGit 4.5.6 was reverted due to a new failing test.  This update will not be applied unless all tests pass in all tested configurations.

Use JGit 4.5.7

---

pom.xml
src/test/java/org/jenkinsci/plugins/gitclient/PushTest.java

Use latest parent pom to assure javadoc builds on JDK 11.0.3.  Merge stable-2.7 branch with its latest changes.

Use parent pom 3.43

---

pom.xml

* compiler
* surefire
* javadoc
Parent pom is well maintained and tracks the needs of many plugins on Java 8 and Java 11.  No need to specify plugin versions in this pom.

Rely on parent pom for plugin versions

---

pom.xml

Add an exclusion for a newer version of ssh-cli-auth required by Jenkins 2.176.1.  Allows compile and test with `mvn clean -Djenkins.version=2.176.1 verify`.

Exclude ssh-cli-auth dep for Jenkins 2.176.1

---

src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java

JGit 5.4.0 throws an exception when trying to delete a submodule with the extra argument to git clean.

Skip clean and assert in JGit submodule clean test

---

pom.xml

Update pom to use latest parent and to update two other dependencies

Use parent pom 3.46

---

src/test/java/org/jenkinsci/plugins/gitclient/GitClientTest.java

Slightly increase test coverage by testing failure cases for `git init`, `git branch`, and `git commit`.

Add exception tests for init, branch, & commit

---

pom.xml

Bumps plugin from 3.46 to 3.47.
Use the latest parent pom.

Bump plugin from 3.46 to 3.47

---

src/test/java/hudson/plugins/git/GitExceptionTest.java

Discovered as part of https://github.com/jenkinsci/bom/pull/36, which runs this plugin’s tests under PCT in a Docker container running as root. (Would also see this if switching `linux` to `maven` in the `buildPlugin` config.)
Verified with
```sh
docker run -v ~/.m2:/var/maven/.m2 -ti --rm --name mvn -e MAVEN_CONFIG=/var/maven/.m2 -v "$PWD":/usr/src/mymaven -w /usr/src/mymaven maven:3.6.1-jdk-8 mvn -Duser.home=/var/maven surefire:test -Dtest=GitExceptionTest
```

GitExceptionTest failed when run as root

---

.dependabot/config.yml
pom.xml

Bumps plugin parent pom version from 3.47 to 3.48.
Use most recent parent pom.

Bump plugin from 3.47 to 3.48

---

.dependabot/config.yml
pom.xml

Dependabot has been quite helpful tracking dependency updates in the repository.  Configure it to propose changes to the stable branch which can then be merged to master.

Add dependabot config and update parent pom

---

Jenkinsfile

Faster build is valuable
Accept that Java 11 on Windows is rare and Windows testing is slower.
Accept that Jenkins 2.164 and later are more common and more interesting.

Reduce test configs 50%

---

src/test/java/hudson/plugins/git/GitExceptionTest.java
src/test/java/org/jenkinsci/plugins/gitclient/FilePermissionsTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientTest.java

Test assumes it is running as an unprivileged user and relies on that for a failure case.  Fix that and release a new version so that the BOM can depend on a released version which includes passing tests.

Fix test failure when running as root user

---

pom.xml

The spotbugs annotation has a transitive dependency on jsr305.  Since the spotbugs dependency is optional, it is not included in the hpi file. However, its transitive dependency is included in the hpi file.  We don't need to include jsr305, so exclude it in the pom.
Switch to use the BOM for the test dependencies as well, consistent with git plugin use of BOM.

Exclude jsr305 from plugin packaging

---

Jenkinsfile

Improve test coverage by testing one configuration with 2.164 and one with 2.176.  Do not increase test time.  Accept that covering less than the full matrix may leave bugs undetected for a few iterations.

Test with Jenkins 2.176.3

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/test/java/org/jenkinsci/plugins/gitclient/CredentialsTest.java

It is generally a poor security practice to embed the username and password in the Git repository https URL, but there are cases where it may be the best solution for a specific problem.
Prior to git client plugin 2.8.5, username and password embedded in the repository URL were ignored or mangled.
This change adds automated tests to confirm that embedded usernanme and password now work.
See also [JENKINS-41066](https://issues.jenkins-ci.org/browse/JENKINS-41066)
Thanks to @ckrams for submitting the original proposal to fix this in #416

Test for JENKINS-56257 in CLI git

---

pom.xml
src/test/java/org/jenkinsci/plugins/gitclient/CredentialsTest.java

The timeout setting in `CredentialsTest` has to be removed because due to parallel running tests individual methods may run slower.

Run tests in parallel to reduce overall execution time

---

pom.xml

Switches from internally maintaining a compilable version number for each component to specifically use the version provided by Jenkins plugin BOM 2.138.2.  Switches plugin version to 2.9.x as a result of that change of BOM.
Updates required Jenkins version from 2.121.1 to 2.138.4, matching the required Jenkins version of Git plugin 3.12.0 and later.
Strategy change is inspired by a desire to move users onto the most heavily tested plugin versions.  Users that don't want to update dependencies are welcome to choose to remain with older versions of this plugin.

Use plugin BOM for dependencies

---

pom.xml
src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/test/java/hudson/plugins/git/GitToolResolverTest.java
src/test/java/org/jenkinsci/plugins/gitclient/CredentialsTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java

No need to complicate the pom file with setting a property, better to adjust the value in the specific context of exactly the test cases which need it.
The CALL_SETSID value only needs to be changed for those test cases which are using a private key with a passphrase.  Private key tests which don't use a passphrase and username/password tests do not need to modify the CALL_SETSID value.
Adjusts tests which had an unexpected dependency on SETSID.

Move SETSID control from pom to test

---

src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java

org.jenkinsci.plugins.gitclient.GitAPITestCase#test_merge_with_message assumed that the commit message was on line 7 of the revision output. But when cli git is globally configured to sign each commit then line 7 is the start of the gpg signature (an empty line)
This fix checks if there is such a signature in the revision output and instead assumes that the commit message is two lines below the end of the signature.

Fix testcase when cli git signs commit

---

pom.xml

Fixes a performance issue when reading configuration and a bug in file system timestamp resolution.
See https://projects.eclipse.org/projects/technology.jgit/releases/5.5.1
Do not rely on ArrayIndexOutOfBoundsException to detect end of input. Config#StringReader relied on ArrayIndexOutOfBoundsException to detect the end of the input. Creation of exception with (deep) stack trace can significantly degrade performance
WorkingTreeIterator: correctly handle different timestamp resolutions [forums 1100344](https://www.eclipse.org/forums/index.php/t/1100344/)

Use JGit 5.5.1

---

pom.xml

Since CONTRIBUTING has said for a long time that tidy:pom is the element sequencing, this makes it so.

Enforce pom formatting

---

pom.xml
src/main/java/hudson/plugins/git/GitTool.java
src/main/java/org/jenkinsci/plugins/gitclient/GitToolConfigurator.java
src/test/java/org/jenkinsci/plugins/gitclient/GitToolConfiguratorJenkinsRuleTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitToolConfiguratorTest.java
src/test/java/org/jenkinsci/plugins/gitclient/JcascTest.java
src/test/resources/org/jenkinsci/plugins/gitclient/configuration-as-code.yaml

Different approach to #426 using a custom Configurator instead of trying to redesign the entire class structure.

[JENKINS-57326] JCasC support for GitTool and subtypes

---

pom.xml

Remove the tidy:check from default build.  Intermittent.

Remove tidy:check - unexplainable failures

---

.github/pull_request_template.md
src/test/java/org/jenkinsci/plugins/gitclient/CredentialsTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java
src/test/java/org/jenkinsci/plugins/gitclient/MergeCommandTest.java

Tests intentionally reuse data from the git client plugin master branch. Now that the README is in adoc format, the file name changes in the tests to match what is stored on the file system.

Switch from README.md to README.adoc in tests

---

.github/pull_request_template.md
src/test/java/org/jenkinsci/plugins/gitclient/CredentialsTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java
src/test/java/org/jenkinsci/plugins/gitclient/MergeCommandTest.java

The automated tests intentionally depend on the content of the git client plugin master branch so that they are testing with real history and real use cases.  One of the dependencies is the precise name of the README file.  The README file is now used as part of the online documentation.  It has changed from markdown to asciidoc syntax to be consistent with the git plugin and to be easier to manage.  
This change fixes the tests in the stable-2.x branch that depend on the name of the README file.  It is a cherry pick of the same fix which was made on the master branch.  If a future release is required from the stable-2.x branch, we want the tests passing on the branch before any other changes are made.

# Fix failing stable-2.x tests

---

pom.xml
src/test/java/hudson/plugins/git/GitExceptionTest.java
src/test/java/org/jenkinsci/plugins/gitclient/StringSharesPrefix.java

Use latest versions of dependencies.
Hamcrest 2.2 upgrade detected some flaws in the eariler implementation.  Those flaws are fixed now.

Use parent pom 3.54

---

src/test/java/org/jenkinsci/plugins/gitclient/cgit/GitCommandsExecutorTest.java

This method was deprecated in Mockito 3.

Replace deprecated Mockito method "verifyZeroInteractions"

---

CONTRIBUTING.adoc
pom.xml

Use the latest parent pom and the latest release of equalsverifier.

Use parent pom 3.55

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/test/java/org/jenkinsci/plugins/gitclient/CredentialsTest.java

Follow-up of #433 and #461
When doing a git merge in a branch containing modified/new LFS objects, git LFS will connect to remote to fetch the LFS objects.
`ssh -- git@github.com git-lfs-authenticate ...`
If the merge is executed without a credential, it fails with an obscure error message:
```
Error downloading object: binary2.bin (d3cf8be): Smudge error: Error downloading binary2.bin (d3cf8beded408772d7d3fbecd0423ca9b26265426f3a101cf263a549fc49e16b): batch request: Permission denied (publickey).: exit status 255
Errors logged to /var/jenkins_home/workspace/reproduce_JENKINS_45228/.git/lfs/logs/20190613T143217.983927423.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: binary2.bin: smudge filter lfs failed
```
This is a very first …

[JENKINS-45228] Add authentication to git merge operations

---

README.adoc

Link to the newly created gitter channel for the git plugin.  We need the gitter channel for Google Summer of Code project mentoring, so we should also include it in the docs.

Add docs badge for new gitter channel

---

pom.xml

Avoid InjectedTest hangs and failures from JTH 2.57
* See [JENKINS-60694](https://issues.jenkins-ci.org/browse/JENKINS-60694)
* See [JENKINS-60754](https://issues.jenkins-ci.org/browse/JENKINS-60754)

[JENKINS-60694] Fix InjectedTest failures from JTH 2.57

---

pom.xml

Remove Jenkins test harness workaround

Use parent pom 3.56

---

.mvn/extensions.xml

Incrementals seem to be no longer publishing for this plugin, maybe this will fix it
https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/git-client/

Bump incrementals version

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java

Points addressed
- a single quote is not allowed between single quotes, even if escaped
- a backslash requires escaping if to be used literally in a reqular expression
This escaping has previously already been used in `quoteUnixCredentials` which was added in commit 62872bccaf3f0e02c663acfdd85be2b38bddf1e8 - see [here](https://github.com/jenkinsci/git-client-plugin/commit/62872bccaf3f0e02c663acfdd85be2b38bddf1e8#diff-4a13310f7c84a9d6e133def48c0aed5aR1449-R1453).
Also see https://www.gnu.org/software/bash/manual/html_node/Single-Quotes.html.
I tested it manually on Linux, with a SSH key and a username/password credential, with a job inside a folder that contains spaces and single quotes.
There is no test infrastructure available yet to test such things automatically - right?

[JENKINS-60316] Fix escaping single quotes in Unix file paths

---

pom.xml
src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java

The default command line git timeout value is a constant that should be readable from Pipeline scripts.

Whitelist CliGitAPIImpl.TIMEOUT for Pipeline

---

src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientTest.java

List of things I have done :
- Deleted Junit 3 test cases in GitAPITestCase
- Added a Junit 4 test in GitClientTest
I have made this PR to clarify that the changes made are in the route of transition. Could @MarkEWaite confirm the way the changes are done?

Convert GitAPITestCase tests from JUnit 3 to JUnit 4

---

src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientTest.java

Junit 3 tests can be sorted according to alphabet order in GitAPITestCase and compared with GItClientTestCases. It would be an efficient idea to change the tests to Junit 4.

Some GitAPITestCase tests were replaced in GitClientTest

---

CONTRIBUTING.adoc

Fix broken hyperlink in the CONTRIBUTING file.

Fix hyperlink to 'Later' in CONTRIBUTING

---

src/main/java/org/jenkinsci/plugins/gitclient/JGitAPIImpl.java
src/test/java/org/jenkinsci/plugins/gitclient/JGitClientTest.java
src/test/java/org/jenkinsci/plugins/gitclient/JGitLightweightTagTest.java

Between Git Client 2.9.0 and 3.0.0 the bundled JGit bumped up from 4.5.7 to 5.5.1. Starting with JGit 4.9.0 upon repo clone, references are packed instead of left loose. All well and good save that `JGitClientAPIImpl.getTags()` trips up over ligthweight tags packed thus, resolving them to null SHA1s. Downstream anything trying to process them is at high risk of an NPE--as in the pre-build merge scenario in the attached JIRA.

[JENKINS-57205] Packed lightweight tags must resolve to meaningful object IDs lest they cause NPEs downstream

---

src/test/java/org/jenkinsci/plugins/gitclient/GitClientCliCloneTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientCloneTest.java

The assertions are checking log messages that are only available from CLI git.  No reason to spend time or energy calling methods that won't generate the necessary logging output.
@rishabhBudhouliya this was an assertion that was missed in the transition from JUnit 3 to JUnit 4. The assertion after the test completes was too subtle.  I like the JUnit 4 style that is expressed in this test now.  It makes explicit checks within the individual test, instead of performing checks at the end of every test.

Move JENKINS-33258 tests into CLI specific tests

---

src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientCliCloneTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientCloneTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientFetchTest.java
src/test/java/org/jenkinsci/plugins/gitclient/WorkspaceWithRepo.java

The localMirror() method clones the remote git client plugin repository into a local copy for use by tests.  Using a remote clone is better than cloning from the local copy because the local copy may be a shallow clone or may be using a sparse checkout.
Unfortunately, the prior implementation of localMirror assumed exclusive access to the target/clone.git directory.  When tests run in parallel, that assumption of exclusive access is wrong.  Multiple tests would attempt to populate the target/clone.git repository.  They would conflict and fail the tests in strange and undesirable ways.
Safely populate the local mirror by cloning to a temporary directory then moving the temporary directory to the intended final destination directory after the clone is complete and after confirming that the …

Safely handle localMirror creation in tests

---

src/test/java/org/jenkinsci/plugins/gitclient/CredentialsTest.java

While exploring a report in [JENKINS-59897](https://issues.jenkins-ci.org/browse/JENKINS-59897) that command line git does PATH resolution on GIT_ASKPASS values which do not include '/' (like Windows, where the value includes '\' instead of '/'), I found some minor items that could be improved in CredentialsTest.
This is test code. It is generally only run by developers that have created the `~/.ssh/auth-data` file to define private repositories and the credentials to use with those private repositories.

Minor improvements to CredentialsTest

---

src/test/java/org/jenkinsci/plugins/gitclient/GitClientTest.java

Git for Windows provides three different installers:
* Windows installer (as an MSI file)
* PortableGit (as a self-extracting exe)
* MinGit (as a self-extracting exe)
Windows installer and PortableGit both include git large file support.  MinGit does not.  If Git LFS is configured and then MinGit is installed, command line git attempts to invoke the smudge filter on checkout.  Since the smudge filter invokes `git-lfs`, it fails with a non-existent command.
Having git lfs configured and not installed will cause repository checkout to fail when the repository includes LFS files.  That failed checkout seems reasonable to me, since a tool is configured but not installed.

Fix windows git LFS tests

---

pom.xml
src/main/java/org/jenkinsci/plugins/gitclient/Git.java
src/main/java/org/jenkinsci/plugins/gitclient/GitClient.java
src/main/java/org/jenkinsci/plugins/gitclient/JGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/RemoteGitImpl.java

The javax annotations from JSR-305 were never finalized and never will be finalized.  The spotbugs team has provided replacements that match with spotbugs usage.
Also updates to spotbugs 4.0.1.
In the spirit of https://github.com/jenkinsci/jenkins/pull/4604

Replace javax annotations with spotbugs annotations

---

src/main/java/hudson/plugins/git/GitObject.java
src/main/java/hudson/plugins/git/Revision.java
src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/Git.java
src/main/java/org/jenkinsci/plugins/gitclient/JGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/MergeCommand.java
src/main/java/org/jenkinsci/plugins/gitclient/jgit/PreemptiveAuthHttpClientConnection.java
src/main/java/org/jenkinsci/plugins/gitclient/trilead/TrileadSession.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientCliCloneTest.java

When spotbugs 4.0.1 was introduced, the threshold was changed to `Low`.  That listed many warning which were not visible at the previous threshold.  This plugin resolves many of those warnings.  Remaining warnings do not seem interesting enough to modify.

Fix spotbugs warnings

---

Jenkinsfile
pom.xml

This pull request switches from requiring Jenkins 2.138.4 as minimum version to require Jenkins 2.204.1 as minimum version.  Using a modern version like 2.204.1 includes the trilead-api separation from the Jenkins core and simplifies testing.
User based justification for choosing 2.204.1 as the new minimum version:
* Over 50% of the 240 000 installations of git client plugin are running git client plugin 3.0.0 or newer.  Over 40 000 git client plugin installations are using Jenkins 2.204.2
* Almost 10x more installations of git client plugin are on Jenkins 2.204.2 than any other single release
Users that are choosing to stay current with the git client plugin are also choosing to stay current with Jenkins releases.  That's a very good thing.  Special thanks to the users for choosing to …

Require Jenkins 2.204.1 or later

---

pom.xml

Switches from using the deprecated hamcrest-core artifact to use the hamcrest artifact that was introduced with hamcrest 2.x
Uses dependencies provided by the parent pom and the 2.190.x bom in all cases where those dependencies are at least as new as the dependencies that were already listed.

Use bom 2.190.x, remove redundant version values

---

pom.xml

Use latest bill of materials to match with the minimum Jenkins version.

Use bom 2.204.x for dependencies

---

pom.xml

Simplify integration with spotbugs and keep current with latest parent pom.

Use parent pom 4.0

---

Jenkinsfile
src/test/java/jmh/benchmark/BenchmarkRunner.java
src/test/java/jmh/benchmark/FolderForBenchmark.java
src/test/java/jmh/benchmark/GitClientFetchBenchmark.java
src/test/java/jmh/benchmark/GitClientFetchVanillaBenchmark.java

Java Micro-benchmarking Harness is a java harness which provides a fairly easy way to run benchmarks and after its integration in the Role Strategy Plugin, it is easier to write them for Jenkins plugins.
- Creation of a test environment: Used FolderForBenchmark to create local git repositories for the lifetime of benchmark test.
- Git operations for evaluation: git fetch
- Added an addition step in JenkinsFile to enable benchmarks on Jenkins CI

Add JMH module: micro-benchmark tests for git-fetch

---

CONTRIBUTING.adoc
src/test/java/jmh/benchmark/GitClientFetchBenchmark.java
src/test/java/jmh/benchmark/GitClientFetchVanillaBenchmark.java
src/test/java/jmh/benchmark/GitClientInitBenchmark.java

This PR was raised to run the benchmarks with a different configuration, the static state class, which provides the setup and tear-down helper functions to each benchmark test, to be shared across the scope of a benchmark instead of a thread.

Change in Scope of state object: from thread level to benchmark level

---

src/test/java/jmh/benchmark/BenchmarkRunner.java
src/test/java/jmh/benchmark/GitClientFetchBenchmark.java
src/test/java/jmh/benchmark/GitClientInitBenchmark.java

The static state class provided by JMH supplements the overhead costs of running a benchmark which are not added in the benchmarking process.
Earlier, the scope of setup() and teardown() methods was set to `Level.Iteration` which means that for each invocation of a benchmark, we create a git client, clone the upstream repository and then test git fetch. This is _certainly_ not ideal. The cost of running a benchmark becomes too high as we are cloning each repository using network for each iteration of a benchmark (5 times is default by JMH) x 2 (fork = 2, all benchmarks are run twice in a separate JVM). 
Now, the state class has been divided into two parts: 
1) ClientState: This static state class provides a git client with a fresh initialized local repository. To keep this local …

Fix abnormally long duration of git fetch benchmark

---

Jenkinsfile

This change will ensure that JMH benchmark module will run benchmarks only if it is the "master" branch or any "gsoc-" related branch.
If only one branch is kept for gsoc in the future, for example gsoc-dev, then we can remove the regex and only search for "gsoc-dev"

Add conditional logic in JenkinsFile to run benchmarks conditionally

---

Jenkinsfile

Limit number of test configurations to 3, but allow Jenkins version to vary randomly among a greater number of versions.  Accepts that the randomness of the testing may show failures that need more investigation.
If this is a relatively large or complex change, start the discussion by explaining why you chose the solution you did and what alternatives you considered.

Test more Jenkins versions on ci.jenkins.io

---

pom.xml

[JENKINS-62767](https://issues.jenkins-ci.org/browse/JENKINS-62767) - need to bundle org.eclipse.jgit.ssh.jsch
Amends #561 to handle https://github.com/eclipse/jgit/commit/8d2d683655e2de17cf465fa46af10e0e56b3aaed.
Not tested in any way, except verifying that the list of bundle JARs now looks saner and includes the missing class.

[JENKINS-62767] Need to bundle org.eclipse.jgit.ssh.jsch

---

CONTRIBUTING.adoc
Jenkinsfile

Will need to find another way to test randomized versions and configurations.  That will be a good excuse to include more platforms in the tests.

Fix incrementals by removing randomized Jenkins version testing

---

Jenkinsfile
Priorities.adoc

Avoid running benchmarks unless the recent commit messages include the word 'benchmark' or we are on the master branch.
This is my alternative to the "run on every branch" we are currently using and the "run only on gsoc-*" branches.  Comments?

Make benchmarks conditional on commit message content

---

pom.xml

The CredentialsTest reports an ugly stack trace during startup because it cannot find the scm-api plugin.  The stack trace does not fail the tests but is a distraction from the purpose of the CredentialsTest.  Include the scm-api asa  test dependency so that the tests do not include that distracting stack trace.
Without the scm-api dependency, the CredentialsTest reports:
```
2.505 [id=31]        WARNING hudson.ExtensionFinder$Sezpoz#scout: Failed to scout jenkins.scm.impl.mock.MockSCMDiscoverBranches$DescriptorImpl
java.lang.ClassNotFoundException: jenkins.scm.api.trait.SCMSourceTraitDescriptor
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
at …
```

Add scm-api dependency for tests

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/jgit/PreemptiveAuthHttpClientConnection.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientTest.java

The GitAPITestCase (JUnit 3) needs to be converted to GitClientTest (JUnit 4).

Reduce a few JUnit 3 tests

---

src/main/java/hudson/plugins/git/GitAPI.java
src/main/java/hudson/plugins/git/IGitAPI.java
src/main/java/org/jenkinsci/plugins/gitclient/GitClient.java
src/main/java/org/jenkinsci/plugins/gitclient/JGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/RemoteGitImpl.java

The previous call to checkout was entirely inside the CliGitAPIImpl and JGitAPIImpl classes.  The replacement used a CheckoutCommand that is not serializable.  This change reverts the replacement.  Issue has been in the git client plugin since git client plugin 3.1.0.
The change development process visited each of the changes in git-client-plugin#399 and retained the changes from that PR which are safe from serialization issues.
Would appreciate review by @dwnusbaum and @fcojfernandez so that we can deliver a new version to fix the issue.
Would love to have suggestions or pointers to ways that this could be tested in the git client plugin test automation.

[JENKINS-60985] - Fix checkout serialization error

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java

Preparation for an eventual warning that should be added to tell users
they are running an outdated version of command line git.  Command line
git versions prior to 2.7 are lacking important features that the
git plugin could use and we'd like to eventually be able to use those
features.

[JENKINS-62587] Log git version value for easier debug

---

README.adoc

The properties are usually "escape hatches" that allow users to restore a risky behavior or to enable something that is intentionally disabled.

Document plugin properties

---

src/main/java/org/jenkinsci/plugins/gitclient/UnsupportedCommand.java
src/test/java/org/jenkinsci/plugins/gitclient/UnsupportedCommandTest.java

This command serves as a way to communicate to the git plugin which git features
are not supported by JGit.
- The reason for not implementing it as a GitCommand implementation is to separate
the need of a `JGitAPIImpl` or `CliGitAPIImpl` to check if a certain additional behaviour
of git is supported or not.
- This class can be instantiated with no need of any information, it can be decorated by a
GitSCMExtension to fill in the features which are not supported.
- Step 1: Define a function within the GitSCMExtension to be implemented by extensions which are not supported by JGit.
ex: ```public void determineSupportForJGit(GitSCM scm, UnsupportedCommand unsupportedCommand) {
}```
- Step 2: Let's take GitLFSPull as an example, implement a function called: 
```@Override
public void …
```

Add a new command: UnsupportedCommand to communicate compatibility of JGit

---

src/test/java/org/jenkinsci/plugins/gitclient/GitClientTest.java

One of the submodule cloning tests, testSubmodulesUsedFromOtherBranches, fails on Windows agents when the Windows workspace is in the default location on a Windows master.
Rather than fight with that directory location, enable core.longpaths for the failing test.  Eventually we'll want to enable core.longpaths on all command line git use from Windows computers.

Fix Windows test failure by enabling core.longpaths

---

README.adoc
src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java

Not consistent with usage in other locations in the plugin that use the ibm.system.encoding Java property rather than an environment variable.  Setting an environment variable may be a little easier.
If this is a relatively large or complex change, start the discussion by explaining why you chose the solution you did and what alternatives you considered.

[JENKINS-63146] Use credentials.file.encoding property for passphrase file

---

README.adoc
src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java

Changes the character set definition properties.  Properties are now:
* `org.jenkinsci.plugins.gitclient.CliGitAPIImpl.user.name.file.encoding`
* `org.jenkinsci.plugins.gitclient.CliGitAPIImpl.user.passphrase.file.encoding`
* `org.jenkinsci.plugins.gitclient.CliGitAPIImpl.user.password.file.encoding`
Keeps the documentation simpler and the code simpler.

[JENKINS-63307] Allow zOS encoding of user name, password, and passphrase

---

src/test/java/org/jenkinsci/plugins/gitclient/RemoteGitImplTest.java

Remote implementation had no tests.  This is the beginning of an attempt to duplicate the remoting problem detected through the Artifactory plugin calls to remote git API.  Does not verify the issue yet, but begins the path to verification.

Add RemoteGitImplTest for a few methods

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/test/java/org/jenkinsci/plugins/gitclient/CliGitAPIImplTest.java
src/test/java/org/jenkinsci/plugins/gitclient/CliGitCommand.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientFetchTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientSampleRepoRule.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientSecurityTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientTest.java
src/test/java/org/jenkinsci/plugins/gitclient/LegacyCompatibleGitAPIImplTest.java
src/test/java/org/jenkinsci/plugins/gitclient/MergeCommandTest.java
src/test/java/org/jenkinsci/plugins/gitclient/PushTest.java
src/test/java/org/jenkinsci/plugins/gitclient/RemoteGitImplTest.java
src/test/java/org/jenkinsci/plugins/gitclient/RemotingTest.java

Use property value rather than property name for the character set.

[JENKINS-63307] Honor property value in zOS credential files

---

README.adoc

#573 was originally opened to handle auto-installing PortableGit, however auto-installing logic was already implemented but not documented. This includes said documentation.

document Installing PortableGit Automatically

---

src/test/java/hudson/plugins/git/GitExceptionTest.java
src/test/java/org/jenkinsci/plugins/gitclient/CliGitAPIWindowsFilePermissionsTest.java
src/test/java/org/jenkinsci/plugins/gitclient/CredentialsTest.java
src/test/java/org/jenkinsci/plugins/gitclient/FilePermissionsTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientSecurityTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientTest.java

The maven surefire plugin reports skipped tests as a WARNING.  That WARNING causes the warnings plugin on ci.jenkins.io to count the skipped test as a warning and display the warning in the job results.
The tests are intentionally skipped so they should not be counted as warnings.  This converts the assertion from a warning to no warning.  The same code is executed as previously, without the maven surefire warning.

Reduce test warning count by not using Assume

---

pom.xml

The 3.5.0 release will include JGit 5.9.0.  JGit updates justify an increase in minor version.

Set plugin version to 3.5.0

---

src/test/java/org/jenkinsci/plugins/gitclient/GitClientTest.java

Final fix needs to be made in git for Windows.
When the git client plugin tests are run in a multi-configuration test, the path names on Windows become longer than the 255 character path name limit imposed by older library versions.  Skip one test in that case.  Final fix needs to be made in git for Windows.

Skip longpath failing test when Windows dir is too long

---

Jenkinsfile

We're not adjusting code based on benchmarks at this time, let's save the execution time on the CI servers until we need to compare JGit and command line git again.

Disable benchmarks on master branch

---

src/main/java/org/jenkinsci/plugins/gitclient/UnsupportedCommand.java
src/test/java/org/jenkinsci/plugins/gitclient/UnsupportedCommandTest.java

The UnsupportedCommand now features a support to convey if JGit should be suggested
as a viable implementation in the scenario where Git Publisher is added as a post build
action.

[JENKINS-63727] Add support to convey compatibility info related to JGit and Git Publisher

---

src/test/java/org/jenkinsci/plugins/gitclient/GitClientTest.java

When command line git does not support remote symbolic references, the test intentionally exits early.  In order to pass the test, it needs to throw the expected exception instead of simply returning. Throw the
expected exception.
Allows tests to run successfully on CentOS 7 with git 1.8.3.

Throw GitException as expected in GitClientTest

---

src/main/java/hudson/plugins/git/GitTool.java
src/main/resources/hudson/plugins/git/GitTool/config.jelly
src/test/java/jmh/benchmark/GitClientFetchBenchmark.java
src/test/java/jmh/benchmark/GitClientFetchVanillaBenchmark.java
src/test/java/jmh/benchmark/GitClientInitBenchmark.java
src/test/java/jmh/benchmark/GitClientLSRemoteBenchmark.java
src/test/java/jmh/benchmark/GitClientRedundantFetchBenchmark.java
src/test/java/org/jenkinsci/plugins/gitclient/CliGitAPIImplTest.java
src/test/java/org/jenkinsci/plugins/gitclient/CredentialsTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientTest.java

Annotate HTTP accessible method with RequirePOST.  Since the method is only needed from a POST context, it should be annotated with @RequirePOST.  The method does not invoke any risky code that might make it a security risk, but it is not useful as a GET method, so require that it must be called with POST.
Also renames several test methods to avoid warnings due to poorly named test methods.

Reduce code scanner warnings

---

src/main/java/hudson/plugins/git/GitTool.java
src/main/java/hudson/plugins/git/IGitAPI.java
src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/GitClient.java
src/main/java/org/jenkinsci/plugins/gitclient/GitURIRequirementsBuilder.java
src/main/java/org/jenkinsci/plugins/gitclient/JGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/JGitApacheTool.java
src/main/java/org/jenkinsci/plugins/gitclient/JGitTool.java
src/main/java/org/jenkinsci/plugins/gitclient/MergeCommand.java
src/main/java/org/jenkinsci/plugins/gitclient/UnsupportedCommand.java

Simply cleanup source code
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. This is simply a reminder of what we are going to look for before merging your code._
If this is a relatively large or complex change, start the discussion by explaining why you chose the solution you did and what alternatives you considered.

Remove redundant code

---

src/main/java/org/jenkinsci/plugins/gitclient/RemoteGitImpl.java

Similarly to https://github.com/jenkinsci/git-plugin/pull/1012 - Stemming from IRC discussion with @timja, it seems that for codebase running on Jenkins core after xstream changes (2.266+) the inherited private `readResolve()` methods that are a problem solved by making them protected: https://github.com/jenkinsci/jep/blob/f52f17b085293543a515f8c62fe458491f8e45c9/jep/228/README.adoc#inherited-private-serialization-methods
I do not know if this change really solves any issues, or how to confirm that at the moment.
Suggested by work and discussion on https://github.com/jenkinsci/envinject-plugin/pull/154

Adapt to xstream changes: change readResolve() from private to protected

---

pom.xml

﻿One LTS version behind the current recommended Jenkins base version.
This is the same minimum Jenkins version required for git plugin 4.5.0.
58% of git client plugin installations are running Jenkins 2.222.4 or newer.
Over one third of the git client plugin installations are running the most recent git client plugin release (3.5.1).  The vast majority of those installations are running 2.222.4 or newer.  Users that are upgrading their git client plugin version are also upgrading their Jenkins versions.
Based on those results, updating the minimum Jenkins version from 2.204.x to 2.222.4 should have very little actual impact on users of the git client plugin.

Require Jenkins 2.222.4 as minimum Jenkins version

---

src/main/java/org/jenkinsci/plugins/gitclient/JGitAPIImpl.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientTest.java
src/test/java/org/jenkinsci/plugins/gitclient/JGitAPIImplTest.java
src/test/java/org/jenkinsci/plugins/gitclient/JGitApacheAPIImplTest.java

The [JGIt 5.10.0 release notes](https://projects.eclipse.org/projects/technology.jgit/releases/5.10.0) announce that ls-remote now reports symrefs. [JGit enhancement 514052](https://www.eclip.se/514052) is implemented in JGit 5.10.0.  Use it to replace the earlier implementation that relied on reading internal data from JGit.

Use JGit 5.10.0 ls-remote to get symbolic refs

---

pom.xml

Since other plugins are already using the plugin bom to require a specific version of the configuration as code plugin and this plugin is already using the plugin bom, there is very little benefit to continuing to separately manage the version of the configuration as code plugin that is optional with the git client plugin.

Use plugin bom for JCasC plugin version

---

src/test/java/org/jenkinsci/plugins/gitclient/GitAPITest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java

Added Class GitAPITest, for migration of GitAPITestCase from JUnit 3 to JUnit 4, added the first test getRemoteUrl

[JENKINS-60940] - Migration of GitAPITests from JUnit 3 to JUnit 4

---

README.adoc

Replace 'master' with 'controller' when it refers to the Jenkins server.

Use controller to refer to the Jenkins server

---

src/test/java/org/jenkinsci/plugins/gitclient/GitAPITest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java

Tests Migrated: 
- testRefExists
- testListRefsWithoutPrefix
- testListRefsWithPrefix
- testDeleteRef
- testCreateRef
- testGetTagMessageMultiLine
- testGetTagMessage
- testTagExists
- testListTagsStarFilter
- testListBranchesContainingRef
- testGetTagNamesSupportsSlashesInTagNames
- testListTagsWithoutFilter
- testListTagsWithFilter
- testDeleteTag
- testDeleteBranch
- testCreateBranch
- testEmptyComment
- testGetRemoteUrl
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. This is simply a reminder of what we are going to look for before merging your code._
If this is a relatively large or complex change, …

[JENKINS-60940] - Migrating Test of GitAPITestCase from JUnit 3 to JUnit 4

---

src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java

Works on my Windows computer in JGit 5.10.0

Remove special case from JGit test

---

src/test/java/org/jenkinsci/plugins/gitclient/GitAPITest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java

Tests Migrated in this PR:
- RevList Tag
- RevList Local Branch
- Checkout Branch Null

Migrating Tests From JUnit 3 (GitAPITesCase) to JUnit 4 (GitAPITest)

---

README.adoc
pom.xml

Jenkins 2.249.1 is a recommended Jenkins base version.  More and more plugins are requiring it as a minimum version.
- Require Jenkins 2.249.1 as minimum version
- Use 3.7.0 as plugin base version
- Improve README for credentials, issue reporting, more
- Rely on spotbugs plugin version from parent pom
- Remove unused slf4jVersion property

Require Jenkins 2.249.1

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java

As detailed in the JIRA ticket, on modern Linux systems which do activate SELinux used as Jenkins controller or build agents, it refuses to check out over git+ssh in setups that work otherwise when SELinux is not enforced. This PR explores active labeling of the temporary private key file so the ssh client would not refuse to read it on such systems.
At least initially, no unit tests are added because hitting this situation requires that a testing system is a modern Linux where `root` (human admin or their distro maintainer) ran `setenforce 1` and possibly other configuration activities.
The trigger for added logic is existence of `/usr/bin/chcon` (hardcoded at the moment, per common Linux distros I could look at), and it should be an inexpensive operation - useless but harmless if …

[JENKINS-64913] Label private key files on SELinux

---

src/main/java/hudson/plugins/git/GitTool.java
src/main/java/org/jenkinsci/plugins/gitclient/Git.java

Replace `Jenkins.getInstance()` with either `Jenkins.get()` or other appropriate non-deprecated replacement.
@MarkEWaite

Cleanup getInstance() references

---

pom.xml

Over 90% of users on last 4 releases are 2.263.1 or newer.  Thanks to http://stats.jenkins.io/pluginversions/git.html for real data on user deployments!
In terms of user adoption, 34% of git plugin users are running one of the most recent 4 releases.  28% of plugin users are running one of the most recent 2 releases.

Require Jenkins 2.263.1

---

src/main/java/hudson/plugins/git/GitAPI.java
src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/GitClient.java
src/main/java/org/jenkinsci/plugins/gitclient/JGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/RemoteGitImpl.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientTest.java

[JENKINS-38699](https://issues.jenkins-ci.org/browse/JENKINS-38699) - Validate .git directory with --resolve-git-dir
As the validation of a git repository presently is checked using `git rev-parse --is-inside-work-tree` but if the .git directory is corrupted then current repository's parent directories are searched for a valid .git directory. To limit/confine the traversal, `--is-inside-work-tree` is replaced by `--resolve-git-dir` which check if path to the .git directory of the current git repository is valid.
Switched from the original implementation as a breaking change to instead add a new API that allows the caller to define if parent directories should be searched for a git repository.  Retains the existing behavior for the CLI git …

[JENKINS-38699] Limit CLI git operations to the workspace

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java

Previous PRs for JENKINS-64913 introduced basic support for SELinux, where key files for SSH may have to be labeled, and temporary files made by git-client-plugin were originally rejected. This new feature came with informational logging, especially noisy in case of failures.
As comments to the JIRA ticket exposed, there are systems and cases where SELinux is present, but "chcon" tool fails to modify labels, but yet somehow the rest of the git+ssh tooling does not mind using the key file as it is and so in the end noise about "chcon" failure is irrelevant.
This PR explores the idea of caching failure details of helpers (starting currently with this "chcon") and only flush them to build log if the actual git operation did not succeed.
_Put an `x` in the boxes that apply. You can also fill …

[JENKINS-64913] CliGitAPIImpl.java: less noise with "/usr/bin/chcon"

---

CHANGELOG.adoc
src/main/java/hudson/plugins/git/IGitAPI.java
src/main/java/org/jenkinsci/plugins/gitclient/LegacyCompatibleGitAPIImpl.java
src/test/java/hudson/plugins/git/BranchTest.java
src/test/java/jmh/benchmark/GitClientRedundantFetchBenchmark.java
src/test/java/org/jenkinsci/plugins/gitclient/CredentialsTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientSecurityTest.java
src/test/java/org/jenkinsci/plugins/gitclient/LegacyCompatibleGitAPIImplTest.java

Improve the terminology used in tests and Javadoc comments so that it describes use of the default branch name.
- Use better names for default branch
- Improve GitAPITest terminology
- Update changelog example branch name
- Use better branch name in Javadoc
- Use better branch name in comments
- Describe repository type more clearly
- Remove disabled experimental test
- Clarify default branch use in tests
- Clarify use of remote branch name in BranchTest
- Use default branch name constant in the test
- Use default branch name constant in test

Improve terminology

---

.github/dependabot.yml

Caffeine 3.0.0 and later require Java 11.  We're not ready to require Java 11.
The caffeine library dependency resolves an upper bounds dependency error that comes from script-security plugin through the most recent bom.  After a future script-security plugin release, this exclusion and the dependencyManagement section for caffeine can be removed.
See https://github.com/jenkinsci/git-client-plugin/pull/704

Exclude caffeine 3.0.0 and later from dep checks

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/test/java/org/jenkinsci/plugins/gitclient/CliGitAPIImplTest.java

The `CliGitAPIImpl` class provides a method `isAtLeastVersion` which returns true is the required git is at-least the cli git version. Since this method have package-private scope thus restricting it's usage outside the plugin/package. To overcome this issue a new public scoped method `compareLeastGitVersion` is create with similar working.

Check the least Cli Git version required 

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java

The CliGitAPIImpl class provides a method `getSSHExecutable` which returns an executable file of ssh installed in Windows environment. Since this method has package-private scope thus restricting it's usage outside the plugin/package. To overcome this issue the method's scope is changed to public.

Scope change of getSSHExecutable method

---

Jenkinsfile
src/test/java/org/jenkinsci/plugins/gitclient/CliGitCommand.java
src/test/java/org/jenkinsci/plugins/gitclient/FilePermissionsTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientFetchTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientTest.java
src/test/java/org/jenkinsci/plugins/gitclient/LegacyCompatibleGitAPIImplTest.java
src/test/java/org/jenkinsci/plugins/gitclient/MergeCommandTest.java

Adapt to alternate default branch names
Command line git 2.32 and later use the `init.defaultBranch` global configuration setting when creating a new repository.  That allows users to define a more inclusive default branch name, like 'main', 'default', or 'baseline'.
Many of the git client plugin tests assume the default branch name is 'master'.  These changes adapt the tests to support other default branch names.
Test this pull request with command line git 2.32.0 or later using the global configuration setting:
```
$ git config --global init.defaultBranch main
$ mvn clean verify
$ git config --global --unset init.defaultBranch
```
- Honor init.defaultBranch in automated tests
- Adapt to alternate default branch names
- Fix a JGit test failure in GitAPITestCase
- Fix MergeCommandTest
- …

Honor defaultBranch configuration

---

src/test/java/org/jenkinsci/plugins/gitclient/CredentialsTest.java
src/test/java/org/jenkinsci/plugins/gitclient/FilePermissionsTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientTest.java

Replacing some unnecessary usages of Guava in tests with their native Java Platform equivalents.

Reduce usages of Guava in tests

---

src/test/java/hudson/plugins/git/GitToolResolverTest.java

I noticed that this test had started failing when running BOM tests against a recent incremental of Jenkins core. It appears that this started failing after jenkinsci/jenkins#5425. This patch corrects the problem so that the test works with both old and new versions of Jenkins core.

Adapting `GitToolResolverTest` to jenkinsci/jenkins#5425

---

src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCliGitNotIntialized.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestNotIntialized.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientTest.java

Update submodule test to match new data.
Submodule definitions updated to be after submodule branches were renamed from 'master' to 'main' in the upstream repositories.
Honor the comment that remoteTracking must be false
Intermittent submodule test failures seem to be related to the use of `remoteTracking` = `true` in one of the randomly selected test paths.  Force it to `false` for this case and watch for other failures of the same style.
* Update submodule test to match new data
* More submodule test updates
* Honor the comment that remoteTracking must be false
Tests are running on multiple operating systems to confirm no additional surprises from operating system and command line git version differences.  Do not merge until results of the multi-operating system tests are reported.

Update submodule test data

---

src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCliGitNotIntialized.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestNotIntialized.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientTest.java

Plugin compatibility tester is an important part of the Jenkins plugin BOM evaluation process.  The change in the `tests/getSubmodules` branch breaks the submodule related tests on released plugin versions.  That disrupts the plugin compatibility tester.
Return to the prior settings that were in the `tests/getSubmodules` branch rather than disrupt PCT.
This reverts commit e208678d925f5bf13432f5ab963345ce782cf308 and 3ede44e2771a256a21ca2f239985f8619981c1fb.

Revert submodule test changes

---

src/test/java/org/jenkinsci/plugins/gitclient/GitClientTest.java

Enabling core.longpaths, setting the Windows registry key for long paths, and more have still not been enough to allow long path operations in git for all cases.

Avoid a long path test failure on Windows

---

pom.xml
src/main/java/hudson/plugins/git/IGitAPI.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientSecurityTest.java
src/test/java/org/jenkinsci/plugins/gitclient/trilead/CredentialsProviderImplTest.java
src/test/java/org/jenkinsci/plugins/gitclient/trilead/SmartCredentialsProviderTest.java

Git is deprecating the git protocol per their [blog post](https://github.blog/2021-09-01-improving-git-protocol-security-github/).
* Replace git://github.com with https://github.com in Javadoc
* Replace git://github.com with https://github.com in tests

Remove git protocol from GitHub URLs

---

pom.xml

Current recommended base version
Improves tests for several plugins

Require Jenkins 2.289.1 or later

---

README.adoc
pom.xml
src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/JGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/jgit/PreemptiveAuthHttpClientConnection.java
src/main/javadoc/overview.html
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitURIRequirementsBuilderTest.java
src/test/java/org/jenkinsci/plugins/gitclient/jgit/PreemptiveAuthHttpClientConnectionTest.java

HTTP protocol should be avoidded because it is easy enough to get a Let's Encrypt certificate to secure a site.  Let's encourage users to run https on all their sites.
* Use noopener with target="blank"
* Use https in docs example
* Use https for javadoc links
* Use https in comments
* Use https in test URLs

Use noopener and https in URLs

---

src/test/java/org/jenkinsci/plugins/gitclient/GitClientTest.java

Git LFS definitely does not support sparse checkout with git lfs 2.3.4.  Known to support sparse checkout with 2.13 and with 3.0.

Improve detection of LFS sparse checkout limits

---

pom.xml
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientTest.java

Recent changes in the parent pom have increased test repeatability but have slowed test execution.  Increase test execution speed by skipping several slow tests on Windows and by running tests in parallel on multiple Java processes.
* Fork for tests, reuse forks
* Test less on Windows for better speed
* Ignore cleanup failure in GitClienTest

Improve test performance

---

pom.xml
src/main/java/hudson/plugins/git/GitTool.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientSampleRepoRule.java

Also remove trailing blank lines at end of file
Systematically prevent the addition of unused imports.

Prevent unused Java import statements

---

.gitignore
src/main/java/hudson/plugins/git/GitTool.java
src/test/java/org/jenkinsci/plugins/gitclient/FilePermissionsTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientFetchTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientTest.java
src/test/java/org/jenkinsci/plugins/gitclient/LegacyCompatibleGitAPIImplTest.java
src/test/java/org/jenkinsci/plugins/gitclient/MergeCommandTest.java
src/test/java/org/jenkinsci/plugins/gitclient/PushSimpleTest.java
src/test/java/org/jenkinsci/plugins/gitclient/PushTest.java
src/test/java/org/jenkinsci/plugins/gitclient/RemoteGitImplTest.java
src/test/java/org/jenkinsci/plugins/gitclient/SubmodulePatternStringTest.java
src/test/java/org/jenkinsci/plugins/gitclient/WarnTempDirValueTest.java
src/test/java/org/jenkinsci/plugins/gitclient/trilead/CredentialsProviderImplTest.java

* [JENKINS-67362](https://issues.jenkins.io/browse/JENKINS-67362) Test with init.defaultBranch value
* Ignore VSCode working files
* Log GitTool redundant initialization
* Use spotless to remove unused imports
* Remove unused variables in tests
* Return a typed collection in test

Adapt tests to new default branch name

---

pom.xml

Simplify maintenance of git client plugin by making its pom file more consistent with the git plugin pom file.
- Define & use gitHubRepo property as is standard for repositories that support incremental delivery
- Remove unnecessary hamcrest exclusion
- Remove jsr305 exclusion

Make pom more consistent with git plugin

---

src/test/java/org/jenkinsci/plugins/gitclient/GitAPITest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCase.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestCliGitNotIntialized.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestForCliGit.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestJGitNotInitialized.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestNotIntialized.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientCliCloneTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientCloneTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientFetchTest.java

Earlier splits of tests from one large file into smaller files did not consider that the tests in the smaller files did not need all the infrastructure that had been included when all the tests were in a single, larger file.

Remove unused assertions and assert methods

---

README.adoc
src/main/java/org/jenkinsci/plugins/gitclient/JGitAPIImpl.java
src/test/java/org/jenkinsci/plugins/gitclient/CliGitAPIImplTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientCliCloneTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientCloneTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientFetchTest.java
src/test/java/org/jenkinsci/plugins/gitclient/JGitAPIImplTest.java
src/test/java/org/jenkinsci/plugins/gitclient/JGitApacheAPIImplTest.java

Uses the JGit timeout implementation to prevent JGit operations from hanging indefinitely.
The JGit timeout implementation has a very different behavior than the timeout implementation for command line git.  The command line git implementation stops once the timeout has expired.  The JGit timeout implementation stops after timeout period has completed with no traffic during the timeout period.
This does not add timeout support to JGit checkout because JGit checkout does not provide a timeout API.

[JENKINS-67466] Add timeout to JGit remote operations

---

.gitignore
CONTRIBUTING.adoc
Jenkinsfile
pom.xml
src/test/java/jmh/benchmark/BenchmarkRunner.java

A JMH test run without a review of the results is not very valuable.  Only run the JMH tests if the property `benchmark.run` is `true`.
Don't run JMH benchmarks unless `benchmark.run`=`true`.  There is very little value to running the Java microharness benchmarks to compare JGit and command line git unless JGit is a new version.
Now that JGit 6.0 has released and requires Java 11, the git client plugin will only be accepting bug fixes from the 5.x line.
Always write JSON to the jmh-report.json file so that it can be visualized with https://jmh.morethan.io/

Run JMH benchmarks only with benchmark.run=true

---

pom.xml

- Revert "Exclude byte-buddy from mockito-core"
- Revert "Bump equalsverifier from 3.8.3 to 3.9"

Revert equalsverifier 3.9

---

pom.xml

* Updates org.eclipse.jgit from 5.13.0.202109080827-r to 5.13.1.202206130422-r
* Updates org.eclipse.jgit.http.server from 5.13.0.202109080827-r to 5.13.1.202206130422-r
* Updates org.eclipse.jgit.http.apache from 5.13.0.202109080827-r to 5.13.1.202206130422-r
* Updates org.eclipse.jgit.lfs from 5.13.0.202109080827-r to 5.13.1.202206130422-r
* Updates org.eclipse.jgit.ssh.jsch from 5.13.0.202109080827-r to 5.13.1.202206130422-r
* [579907](https://eclip.se/579907) AmazonS3: Add support for AWS API signature version 4
* Fix connection leak for smart http connections
* [579445](https://eclip.se/579445) Remove stray files (probes or lock files) created by background threads
* [578511](https://eclip.se/578511) Stop initCause throwing in readAdvertisedRefs
* [577937](https://eclip.se/577937) …

Bump jgit.version from 5.13.0 to 5.13.1

---

README.adoc
src/main/java/org/jenkinsci/plugins/gitclient/verifier/AbstractCliGitHostKeyVerifier.java

https://issues.jenkins.io/browse/JENKINS-69149
https://github.com/jenkinsci/git-client-plugin/commit/88f52c6c9b18bca4ad210e3b9910a49433583fd9#commitcomment-79586978

[JENKINS-69149] Older SSH implementations don't support accept-new

---

src/test/java/org/jenkinsci/plugins/gitclient/GitAPICliGitNotIntializedTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPIForCliGitTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPIJGitNotInitializedTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPINotIntializedTest.java

The JUnit 4 transition renamed these test classes and the maven surefire plugin was not running the tests because they did use the expected class name pattern.

Use expected test class names

---

src/test/java/org/jenkinsci/plugins/gitclient/CredentialsTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestUpdate.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestUpdateCliGit.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientCloneTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientFetchTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientTest.java
src/test/java/org/jenkinsci/plugins/gitclient/verifier/AcceptFirstConnectionVerifierTest.java
src/test/java/org/jenkinsci/plugins/gitclient/verifier/KnownHostsFileVerifierTest.java
src/test/java/org/jenkinsci/plugins/gitclient/verifier/ManuallyProvidedKeyVerifierTest.java
src/test/java/org/jenkinsci/plugins/gitclient/verifier/NoHostKeyVerifierTest.java

Tests included safeguards for conditions that are no longer supported, like running the tests on CentOS 6 or other operating systems that are no longer supported by the operating system provider.  No need to have the additional conditionals for conditions that are not changing.
- Show more information if test fails
- Remove unused imports
- Simplify assertions
- Use assertThrows instead of try / catch
- Credentials are always supported with the supported CLI git versions
- Do not test for CLI git versions older than 1.8.3

Simplify test assertions

---

pom.xml

A recommended version and resolves security vulnerabilities.

Require Jenkins 2.332.4 or later

---

Jenkinsfile
pom.xml
src/test/java/org/jenkinsci/plugins/gitclient/verifier/AcceptFirstConnectionVerifierTest.java
src/test/java/org/jenkinsci/plugins/gitclient/verifier/KnownHostsFileVerifierTest.java
src/test/java/org/jenkinsci/plugins/gitclient/verifier/ManuallyProvidedKeyVerifierTest.java
src/test/java/org/jenkinsci/plugins/gitclient/verifier/NoHostKeyVerifierTest.java

https://github.com/jenkinsci/bom/pull/1338#issuecomment-1198016897 notes that there is an automated test failure in the bill of materials and plugin compatibility tests.  This change is trying to duplicate that failure on ci.jenkins.io.
The first commit in this pull request will be considered "successful" if the build status is failing for the first run.
* [![Build Status](https://ci.jenkins.io/buildStatus/icon?job=Plugins%2Fgit-client-plugin%2FPR-880&build=1)](https://ci.jenkins.io/job/Plugins/job/git-client-plugin/view/change-requests/job/PR-880/1/) (build 1 aborted for build 2)
* [![Build Status](https://ci.jenkins.io/buildStatus/icon?job=Plugins%2Fgit-client-plugin%2FPR-880&build=2)](https://ci.jenkins.io/job/Plugins/job/git-client-plugin/view/change-requests/job/PR-880/2/) - build 2 …

Use container agent for CI build

---

src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestUpdateCliGit.java

This PR just re-applies the logical change of PR #886 into the new test case file, after the original fix got lost with merge of #824 with its mass renaming.

[JENKINS-69193] GitAPITestUpdateCliGit: rely less on strict wording of messages from git CLI tool

---

Jenkinsfile
src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java

* Java 17 with the most recent LTS - 2.361.1
* Java 11 with the previous LTS - 2.346.3
* Java 8 with the default provided by jenkins.version - 2.332.4
- ~~I have referenced the Jira issue related to my changes in one or more commit messages~~
- ~~I have added tests that verify my changes~~
- ~~I have interactively tested my changes~~

Test a wider range of Jenkins versions in CI

---

pom.xml

The gson package is not enabled for serialization in Jenkins, so the vulnerability reported as [CVE-2022-25647](https://nvd.nist.gov/vuln/detail/CVE-2022-25647) is unlikely to have any impact on the git client plugin.  However, it is easier for users running security scans if we upgrade the gson library from 2.8.8 to 2.8.9.
See the [gson 2.8.9 changelog](https://github.com/google/gson/blob/master/CHANGELOG.md#version-289) for more details.

[JENKINS-69706] Use gson 2.8.9 to satisfy security scanners

---

pom.xml

The spotbugs inclusion from the parent no longer includes the jsr305 jar as a transitive dependency.  Safe to rely on it.
- ~~I have interactively tested my changes~~

Rely on spotbugs from parent pom

---

src/main/java/org/jenkinsci/plugins/gitclient/verifier/package-info.java

Describe org.jenkinsci.plugins.gitclient.verifier in the javadoc so that it matches the javadoc of the other packages.

Add verifier package description for javadoc

---

src/test/java/org/jenkinsci/plugins/gitclient/CliGitAPIImplTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestUpdate.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestUpdateCliGit.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientTest.java

A recent Git security fix broke some tests
```
fatal: transport 'file' not allowed
```
I guess because agent templates were updated @dduportal?
The trick in https://github.com/commercialhaskell/stack/pull/5909 did not work for me.
There was another test that failed locally for me. No clue what it means.
You can see the test failures in #919.

Ignoring failing tests

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/test/java/org/jenkinsci/plugins/gitclient/CliGitAPIImplTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestUpdate.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestUpdateCliGit.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientTest.java

Allow local git clones to use the file:// protocol by setting protocol.file.allow=always in the global git configuration for the current user.
Command line git 2.38.1 and patches to earlier versions disallow local git submodule cloning with the file:// protocol. The change resolves a security issue but that security issue is not a threat to these tests.

Allow file:// clones of submodules in tests

---

pom.xml

Preparing for https://github.com/jenkinsci/plugin-pom/pull/634 in which I plan to remove the managed dependency on Objenesis from the plugin parent POM. I do not think it makes sense to manage this dependency in the plugin parent POM, since unlike the other test dependencies managed there (e.g., Hamcrest, JUnit, and Mockito) it is not very common for plugins to consume this dependency directly. Better for the few that do to manage the version on their own.

Explicitly specify Objenesis version rather than consuming it from plugin parent POM

---

src/test/java/jmh/benchmark/FolderForBenchmark.java

Introduced in 107bbe0b4a574d94de7171078aabfdba1cdd86eb when I missed that the folder argument could be null.  When the folder argument is null, the previous method uses the system temporary directory. This change does the same.
JMH tests will be used to compare JGit 5.13.1 and JGit 6.4.0.  This change will allow the JGit 5.13.1 baseline tests to be performed.

Fix JMH environment test setup

---

src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestUpdate.java
src/test/java/org/jenkinsci/plugins/gitclient/WorkspaceWithRepo.java

Do not attempt to use the local repository as a reference repository when the local repository is a shallow clone.  A shallow clone repository has no content to offer as a reference.  Fixes 64 test failures when the test repository is a shallow clone.
https://github.com/jenkinsci/bom/pull/1613 describes the experiment to run the plugin compatibility tests with shallow clones.
https://github.com/jenkinsci/git-plugin/pull/1365 implemented a similar change in the git plugin so that shallow cloned repositories will not fail the tests in that plugin.
Will make a few tests in a shallow repository a little slower because they will require a full clone of the git client plugin repository rather than reusing the existing clone in the test workspace.  Doubtful that the performance difference will …

Allow tests from shallow clone repos

---

CONTRIBUTING.adoc
Jenkinsfile
README.adoc
pom.xml
src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/JGitAPIImpl.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientTest.java

- Test Java 11 and Java 17 in CI
- Do not include JGit or Java 8 links in Javadoc
- Remove site generation customization
- Require Jenkins 2.371.4 or newer
- Use JGit 6.4.0
- Update JGit javadoc link to JGit 6.4.0
- Remove Java 8 reference from contributing guide
Switch from Java 8 to Java 11 as minimum Java version.  Use JGit 6.4.0 instead of JGit 5.13.x.
JGit project has dropped support for Java 8 with the release of JGit 6.0.  It is time to run exclusively on Java 11 or newer.

Require Java 11 and Jenkins 2.361.4 or newer

---

pom.xml

A [2020 blog post from a jsch consumer](https://www.matez.de/index.php/2020/06/22/the-future-of-jsch-without-ssh-rsa/) notes that the maintainers of the jsch library are not responding to requests.  The jsch library was last released in November 2018.
The JGit project provides the [org.eclipse.jgit.ssh.apache library](https://git.eclipse.org/r/plugins/gitiles/jgit/jgit/+/master/org.eclipse.jgit.ssh.apache/) in addition to the [org.eclipse.jgit.ssh.jsch library](https://git.eclipse.org/r/plugins/gitiles/jgit/jgit/+/master/org.eclipse.jgit.ssh.jsch/).  The org.eclipse.jgit.ssh.apache library appears to be a complete replacement for git client plugin use cases.  The JGIt project has declared [their jsch library is deprecated](https://git.eclipse.org/r/plugins/gitiles/jgit/jgit/+/master/org.ec …

[JENKINS-69159] Replace jsch with Apache Mina ssh in JGit

---

src/test/java/org/jenkinsci/plugins/gitclient/GitAPITest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientCloneTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientFetchTest.java

The increases are minor changes that cover a few more JGit methods without significantly increasing test time.
- Call prune() instead of prune(true) at least once
- Test null depth for shallow fetch
- Test shared() in addition to shared(true)
- Call tags(boolean) from a test
- Test push.force()

Increase test coverage

---

src/main/java/org/jenkinsci/plugins/gitclient/cgit/GitCommandsExecutor.java

Cleaning up after #686 now that the baseline is on a recent version of Guava.

Remove unnecessary use of reflection

---

src/main/resources/hudson/plugins/git/GitTool/global.jelly

* Removes the entry wrapper so the title isn't repeated, relates to https://github.com/jenkinsci/jenkins/pull/7716
Also replaces a reference to the deprecated method `getApplicableDesccriptors` (note the spelling error in `Desccriptors`) with the standard method `getApplicableDescriptors`

Remove duplicated 'Git installations' title in Tools page

---

src/main/java/org/jenkinsci/plugins/gitclient/verifier/AcceptFirstConnectionVerifier.java
src/main/java/org/jenkinsci/plugins/gitclient/verifier/KnownHostsFileVerifier.java
src/main/java/org/jenkinsci/plugins/gitclient/verifier/ManuallyProvidedKeyVerifier.java
src/main/java/org/jenkinsci/plugins/gitclient/verifier/NoHostKeyVerifier.java

Bitbucket addition of an ED-25519 host key lead me to find the existing log files insufficient to confirm that the host key was being used as expected.

Add host key logging

---

pom.xml

Simplify the pom file by removing the unnecessary argLine property

Remove unnecessary argLine property from pom file

---

src/test/java/org/jenkinsci/plugins/gitclient/cgit/GitCommandsExecutorTest.java

Guava 32.0.0 from https://github.com/jenkinsci/jenkins/pull/8064 turns up the following new PCT failure:
```
java.lang.AssertionError: 
Expected: is sameInstance(<java.lang.InterruptedException: some interrupt>)
but: was null
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
at org.jenkinsci.plugins.gitclient.cgit.GitCommandsExecutorTest.commandWasInterrupted(GitCommandsExecutorTest.java:209)
```
likely due to google/guava@8f0350a21a713e2367cbcb526aa7bc5bf381fcb9. There does not seem to be any issue in production code here; rather, the test is overly fussy about what kind of `InterruptedException` it is getting. Loosening up the test allows it to work in both the old and new versions of Guava. This will need to …

Forward compatibility with Guava 32.0.0

---

src/test/java/hudson/plugins/git/GitToolResolverTest.java
src/test/java/hudson/plugins/git/GitToolTest.java
src/test/java/org/jenkinsci/plugins/gitclient/CredentialsTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitJenkinsRuleTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitToolConfiguratorJenkinsRuleTest.java

A confusing naming convention was being used.  Use the same naming convention as the git plugin and the same naming convention that is used in many plugins.

Name JenkinsRule variable consistently

---

src/test/java/org/jenkinsci/plugins/gitclient/GitClientMaintenanceTest.java

Command line git 2.41 adds a new file suffix when it writes a loose object.  The new file suffix is not relevant to the assertion in this test.  Simplify the assertion to check that there is at least one file with the '.idx' suffix and at least one file with the '.pack' suffix.  Other files are allowed and other suffixes are allowed.

Simplify loose objects test for CLI git 2.41

---

pom.xml
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientMaintenanceTest.java

- Use collector consistently in the maintenance test
- Set file encoding for tests
- Remove flawed character set assertion
Tests were broken when I removed the source file character set encoding argument, though the deleted assertions were incorrect long before that.

Fix character set tests

---

README.adoc

Portable git reference is from older documentation

Use correct name for MinGit in documentation

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java

Thanks to @StefanSpieker for the pointer to the [deprecated core API usage report](https://ci.jenkins.io/job/Reporting/job/deprecated-usage-in-plugins/) where it shows that `proxy.getPassword()` is the only deprecated core API used in the git client plugin.  Easy to fix.  
Not tested by automation.  Adding useful proxy configuration tests is beyond the scope of this pull request.
Tested interactively by temporarily adding a logging statement to report the value of `userInfo` after the assignment.  I defined a proxy in the "Advanced settings" of the plugin manager page, then attempted to clone a git repository over https.  The logging statement displayed the expected value in the userInfo string.  I removed the temporary logging statement.

Use proxy.getSecretPassword(), not deprecated proxy.getPassword()

---

pom.xml

Do not bundle the gson-api jar  file as a transitive dependency when there is already a gson-api Jenkins plugin available.
Added to bom so that the version number can be retrieved from the plugin bill of materials in a future BOM release:
* https://github.com/jenkinsci/bom/pull/2723

Use gson-api plugin instead of bundling gson-api jar

---

src/main/javadoc/overview.html

The JGit project has moved their wiki to GitHub.

Fix Javadoc link to JGit user guide

---

README.adoc

Note that Jenkins no longer supports any known operating systems with an OpenSSH version prior to OpenSSH 7.6.  The `accept-new` option is available on all the implementations of OpenSSH on operating systems supported by Jenkins.
Add the most important option to resolve the issue, upgrade to a supported operating system.
List more operating systems so that web searches will find the page for those operating systems.
Link to the operating system end of life blog post.
Correct the name of Amazon Linux.
* [JENKINS-72546](https://issues.jenkins.io/browse/JENKINS-72546) is a reminder that this information is still useful and still needed.
* [JENKINS-69149](https://issues.jenkins.io/browse/JENKINS-69149) is an earlier report of the same issue.

Operating systems with outdated OpenSSH are no longer supported

---

src/main/java/hudson/plugins/git/Branch.java

I used `String.format()` function for better consistency and it is more understandable.
Instead of relying on the `hashCode` of the superclass I've used the `Object.hash()` method to generate a hashcode. I think it is easier to understand and more explicit.

Calculate hashCode with arguments that are consistent with equals

---

.github/workflows/release-drafter.yml

Using this condition will help avoid unnecessary runs in repositories where the workflow is not applicable. This same check is implemented in [gitlab-plugin](https://github.com/jenkinsci/gitlab-plugin) project in file https://github.com/jenkinsci/gitlab-plugin/blob/master/.github/workflows/release-drafter.yml

Only run actions from jenkinsci organization

---

src/main/java/hudson/plugins/git/Revision.java

Simplify the implementation of `Revision.clone()`

Simplify Revision.clone() implementation

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java

Accessing message in exception handler is missing null check. 
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. This is simply a reminder of what we are going to look for before merging your code._

[Jenkins-72819] Fix NPE in CliGitAPIImpl.launchCommandIn() caused by InterruptedException

---

src/main/java/org/jenkinsci/plugins/gitclient/JGitAPIImpl.java

Improve the phrasing of two exceptions related to JGit.

Minor phrasing change in a JGit specific exception message

---

src/main/java/org/jenkinsci/plugins/gitclient/GitClient.java

No reason to have warnings in javadoc generation.

Fix javadoc warning

---

src/test/java/org/jenkinsci/plugins/gitclient/CliGitCommand.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPIForCliGitTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestUpdate.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientFetchTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientMaintenanceTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientSampleRepoRule.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientTest.java
src/test/java/org/jenkinsci/plugins/gitclient/JGitLightweightTagTest.java
src/test/java/org/jenkinsci/plugins/gitclient/LegacyCompatibleGitAPIImplTest.java
src/test/java/org/jenkinsci/plugins/gitclient/MergeCommandTest.java
src/test/java/org/jenkinsci/plugins/gitclient/PushTest.java
src/test/java/org/jenkinsci/plugins/gitclient/RemoteGitImplTest.java
src/test/java/org/jenkinsci/plugins/gitclient/WorkspaceWithRepo.java

work around https://bugs.eclipse.org/bugs/show_bug.cgi?id=581483
If the current git setup has SSH based code signing enabled (gpg.format=ssh)[1] then the tests fail (even though not signing) as jgit fails to parse the config with an error like:
```
java.lang.IllegalArgumentException: Invalid value: gpg.format=ssh
at org.eclipse.jgit.lib.DefaultTypedConfigGetter.getEnum(DefaultTypedConfigGetter.java:103)
at org.eclipse.jgit.lib.Config.getEnum(Config.java:454)
at org.eclipse.jgit.lib.GpgConfig.<init>(GpgConfig.java:86)
at org.eclipse.jgit.api.CommitCommand.processOptions(CommitCommand.java:662)
at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:189)
at org.jenkinsci.plugins.gitclient.JGitAPIImpl.commit(JGitAPIImpl.java:487)
at …
```

Tolerate default commit signing with SSH in tests

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/GitClient.java
src/main/java/org/jenkinsci/plugins/gitclient/JGitAPIImpl.java
src/test/java/org/jenkinsci/plugins/gitclient/CliGitCommand.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientTest.java

Local configuration changes that are performed in GitClientTest allow the tests to run in environments where commit signing is the user or system level default.  Remove those local configuration changes at the end of the tests, since they were specifically performed for the test.

Remove local repo config changes at end of tests

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/GitClient.java
src/main/java/org/jenkinsci/plugins/gitclient/SubmoduleUpdateCommand.java
src/test/java/org/jenkinsci/plugins/gitclient/CliGitAPIImplTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPIForCliGitTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestUpdate.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientFetchTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientSecurityTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientTest.java
src/test/java/org/jenkinsci/plugins/gitclient/JGitAPIImplTest.java
src/test/java/org/jenkinsci/plugins/gitclient/JGitApacheAPIImplTest.java

The git client plugin no longer needs to support command line git older than 2.11 because all the operating systems supoprted by Jenkins include command line git 2.11 or newer.  No need for conditionals to check for older versions.
The command line git versions supported by the git client plugin all include symref functionality.  No need to test for support of symref, since all supported versions of command line git include it.
https://www.jenkins.io/blog/2023/05/30/operating-system-end-of-life/ is the May 2023 blog post that announced the end of life for RHEL 7 and its derivatives.

Remove outdated tests

---

src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestUpdateCliGit.java

[Prior discussion](https://github.com/jenkinsci/git-client-plugin/pull/1122#discussion_r1644289890) notes that the sleep does not actually help the test other than to delay its completion.
This reverts commit fb9d2ca1189fd2c02e593ffda9922b3cf10fca45.

Revert added 3 second delay in test

---

pom.xml
src/main/java/org/jenkinsci/plugins/gitclient/JGitAPIImpl.java

JGit 7.0.0 requires Java 17.  Jenkins 2.463 requires Java 17.
Use the plugin bill of materials from 2.462.x because it is the closest we have to 2.463.  The plugin is expected to work with any release 2.463 or later.

Use JGit 7.0.0, require Java 17 and Jenkins 2.463 or newer

---

src/main/java/hudson/plugins/git/Branch.java
src/main/java/hudson/plugins/git/IndexEntry.java
src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/GitToolConfigurator.java
src/main/java/org/jenkinsci/plugins/gitclient/JGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/RemoteGitImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/jgit/CredentialsProviderImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/jgit/PreemptiveAuthHttpClientConnection.java
src/main/java/org/jenkinsci/plugins/gitclient/jgit/SmartCredentialsProvider.java
src/main/java/org/jenkinsci/plugins/gitclient/verifier/KnownHostsFileVerifier.java
src/main/java/org/jenkinsci/plugins/gitclient/verifier/ManuallyProvidedKeyVerifier.java
src/main/java/org/jenkinsci/plugins/gitclient/verifier/SshHostKeyVerificationStrategy.java
src/test/java/jmh/benchmark/BenchmarkRunner.java
src/test/java/jmh/benchmark/FolderForBenchmark.java
src/test/java/org/jenkinsci/plugins/gitclient/FilePermissionsTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestUpdate.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITestUpdateCliGit.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientMaintenanceTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientSecurityTest.java
src/test/java/org/jenkinsci/plugins/gitclient/GitClientTest.java
src/test/java/org/jenkinsci/plugins/gitclient/NetrcTest.java
src/test/java/org/jenkinsci/plugins/gitclient/jgit/AuthzTest.java
src/test/java/org/jenkinsci/plugins/gitclient/verifier/AcceptFirstConnectionVerifierTest.java
src/test/java/org/jenkinsci/plugins/gitclient/verifier/KnownHostsFileVerifierTest.java
src/test/java/org/jenkinsci/plugins/gitclient/verifier/KnownHostsTestUtil.java
src/test/java/org/jenkinsci/plugins/gitclient/verifier/NoHostKeyVerifierTest.java

[Open Rewrite migrate to Java 17](https://docs.openrewrite.org/running-recipes/popular-recipe-guides/migrate-to-java-17) provided the transformations and they all pass automated tests.
Several nice readability improvements are provided by Java 17.
I would like to include these changes in the 6.0.0 git client plugin release, since it will require Java 17.  @olamy or @rsandell could you review and approve?
Automated tests pass.

Use Java 17 features in source code

---

src/main/java/org/jenkinsci/plugins/gitclient/AbstractGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/JGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/LegacyCompatibleGitAPIImpl.java

Reduce compiler warnings about deprecations and declare them consistently.
Opened the generated javadoc in a web browser and navigated briefly.  Deprecated items are shown correctly.

Annotate deprecated methods

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java

Also replaces a StringUtils use with a Java String call.
Confirmed that automated tests pass.

Replace deprecated getPassword() with getSecretPassword()

---

src/main/java/org/jenkinsci/plugins/gitclient/JGitAPIImpl.java

No reason to be inconsistent in the source file, sometimes using the prefix and sometimes avoiding the prefix.
Confirmed that automated tests pass.

Do not prefix a static import reference with its class

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/JGitAPIImpl.java

The JGit 7.0.0 upgrade reminded me that it is unwise to depend on deprecated methods from JGit because they will eventually be removed.  Better to stop using the deprecated methods now and avoid problems in the future.
Confirmed that automated tests pass.

Use non-deprecated JGit methods to get references

---

src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java

Use static field instead of hard-coded string for temp directory.
I saw in our Jenkins instance `@tmp` folders for Git projects since we changed the [hudson-slaves-workspacelist system property](https://www.jenkins.io/doc/book/managing/system-properties/#hudson-slaves-workspacelist) from `@` to `_`.  So I did not verify that this is the only reason, but it is a minor bug anyhow which is quite easy to fix.

Use static field instead of hardcoded string for workspace temp dir

---

pom.xml
src/test/java/org/jenkinsci/plugins/gitclient/JGitLightweightTagTest.java

Reverts jenkinsci/git-client-plugin#1220
Null pointer exception is reported from JGit 7.1.0 API change in DiffFormatter. See the test failure with the command:
```
LINE=weekly PLUGINS=warnings-ng TEST=GitForensicsITest bash local-test.sh
```
Reverting the change so that the master branch continues to pass BOM tests.

Revert "Bump jgit.version from 7.0.0.202409031743-r to 7.1.0.202411261347-r"

---

pom.xml
src/test/java/org/jenkinsci/plugins/gitclient/GitClientSecurityTest.java
src/test/java/org/jenkinsci/plugins/gitclient/verifier/AcceptFirstConnectionVerifierTest.java
src/test/java/org/jenkinsci/plugins/gitclient/verifier/KnownHostsFileVerifierTest.java
src/test/java/org/jenkinsci/plugins/gitclient/verifier/KnownHostsTestUtil.java
src/test/java/org/jenkinsci/plugins/gitclient/verifier/ManuallyProvidedKeyVerifierTest.java
src/test/java/org/jenkinsci/plugins/gitclient/verifier/NoHostKeyVerifierTest.java

Test host verifiers with a randomly selected ssh provider.
The bitbucket.org ssh provider is blocking access from the ci.jenkins.io agents.  That causes tests to fail. Use other ssh providers.
Reduce the load on ssh providers by only testing one in ten times.  Spread the load by using a randomly selected ssh provider instead of always using the same ssh provider.
Also includes other test improvements detected while fixing the failing tests.
* Add mockito-core javaagent for future Java compatibility.  [Mockito javadoc](https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html#0.3) warns that Java version 21 and later report a warning when trying to use Mockito without the javaagent. Followed the instructions in their documentation to add mockito javaagent.
* Remove …

Remove bitbucket.org from host key verification tests

---

src/test/java/org/jenkinsci/plugins/gitclient/verifier/KnownHostsFileVerifierTest.java
src/test/java/org/jenkinsci/plugins/gitclient/verifier/KnownHostsTestUtil.java
src/test/java/org/jenkinsci/plugins/gitclient/verifier/ManuallyProvidedKeyVerifierTest.java

No issues have been detected in local execution of the known hosts tests.  Don't reduce the detection opportunities in local development environments or in environments that are not one of the ci.jenkins.io servers.
Confirmed that tests are executed locally and not skipped.  Rely on ci.jenkins.io test run to confirm that tests are skipped as expected when run there.

Always run known hosts tests locally

---

src/test/java/org/jenkinsci/plugins/gitclient/JGitLightweightTagTest.java

Prepare for JGit 7.2.0 where the `packRefs()` method will be publicly available instead of requiring a JGit internal API.
Document that the `packRefs()` call is required in order to confirm that the previous bug in JGitAPIImpl is still fixed.  I reverted the fix and confirmed that without the call to `packRefs()` the bug is not shown by the test.
Assert that the set of tags has the correct size.
Automated tests pass and the set of diffs that will be needed for JGit 7.2.0 are reduced a little bit.

Minor improvements to JGitLightweightTagTest

---

README.adoc
src/main/java/org/jenkinsci/plugins/gitclient/verifier/AcceptFirstConnectionStrategy.java
src/main/java/org/jenkinsci/plugins/gitclient/verifier/KnownHostsFileVerificationStrategy.java
src/main/java/org/jenkinsci/plugins/gitclient/verifier/ManuallyProvidedKeyVerificationStrategy.java
src/main/java/org/jenkinsci/plugins/gitclient/verifier/NoHostKeyVerifier.java
src/main/java/org/jenkinsci/plugins/gitclient/verifier/SshHostKeyVerificationStrategy.java

[JENKINS-73923](https://issues.jenkins.io/browse/JENKINS-73923) notes that the [git client plugin extensions page](https://jenkins.io/doc/developer/extensions/git-client/) has no documentation.  It says "This extension point has no Javadoc documentation".
Provide the documentation for the extension point and the four implementations of the extension point so that extension point documentation will include documentation after the next release of the git client plugin.
Much of the text is copied from the README or derived from the text in the README.
Checked that the Javadoc renders as expected in Chrome.

[JENKINS-73923] Add javadoc for SSH host key verification strategies

---

pom.xml

Causes plugin BOM tests to fail with a JVM crash.  Compatibility with a future condition is much less important than having tests that run successfully now.
This reverts commit bfde394bae9900335e4e61efab057d9c5cbc5d55.
Confirmed that the JVM crash in the plugin BOM is resolved by this change.

Fix JVM crash in plugin BOM testing

---

src/test/java/org/jenkinsci/plugins/gitclient/cgit/GitCommandsExecutorTest.java

Use real objects instead of mock objects.
Use JUnit 4.13 assertThrows so that try / catch is not needed for exception testing.
Confirmed that tests pass on my Linux computer with Java 21.  Rely on ci.jenkins.io to test Windows with Java 17.

Replace mockito in GitCommandsExecutorTest

---

src/test/java/org/jenkinsci/plugins/gitclient/cgit/GitCommandsExecutorTest.java

Assure that any failures clearly identify themselves.
Replace two utility methods with calls to construct good and bad command objects.
Confirmed that automated tests pass on Linux with Java 21.  Rely on ci.jenkins.io for Windows tests.

Use test name in GitCommandsExecutorTest test data

---

src/test/java/org/jenkinsci/plugins/gitclient/verifier/AcceptFirstConnectionVerifierTest.java
src/test/java/org/jenkinsci/plugins/gitclient/verifier/KnownHostsFileVerifierTest.java
src/test/java/org/jenkinsci/plugins/gitclient/verifier/ManuallyProvidedKeyVerifierTest.java
src/test/java/org/jenkinsci/plugins/gitclient/verifier/NoHostKeyVerifierTest.java

The GitHub SSH abuse prevention system rejects connections from the tests when they are run on ci.jenkins.io.  These tests should only be run as end to end acceptance tests but they are not too disruptive (for now) to continue to be included in the default tests.
Additional tests should be created that use test containers so that they can use the ssh connection on the test container instead of using the GitHub.com SSH servers.
Unfortunately, I can't prioritize that test rewrite now, so these tests are disabled on ci.jenkins.io.
Confirmed that automated tests pass locally where the tests are not excluded.  Final confirmation on ci.jenkins.io where the tests will fail if not excluded.

Skip ssh host tests on ci.jenkins.io

---

README.adoc

Git for Windows' wiki pages were migrated in https://github.com/git-for-windows/git-for-windows.github.io/pull/59.

Replace outdated links to Git for Windows' wiki

---

src/main/java/org/jenkinsci/plugins/gitclient/JGitAPIImpl.java

While evaluating an open file leak in JGit 7.2.0, I found several places in the JGitAPIImpl repository operations that could be simplified by using the Java try with resources facility instead of managing the repository closing inside JGitAPIImpl.  These changes do not resolve the open file leak in JGit 7.2.0, but they make it easier to reason about the open repositories in JGitAPIImpl.  It is intended that this changes no behavior, since the previous implementation was also believed to be cleanly and correctly closing file descriptors.
This pull request is extracted from:
* https://github.com/jenkinsci/git-client-plugin/pull/1262
Best reviewed with [whitespace differences suppressed](https://github.com/jenkinsci/git-client-plugin/pull/1269/files?w=1) by adding the `?w=1` argument on the …

Use try with resources in JGit

---

src/test/java/org/jenkinsci/plugins/gitclient/verifier/KnownHostsTestUtil.java

Microsoft Azure DevOps has transitioned from visualstudio.com as their base URL to dev.azure.com as base URL.  Include that base URL in the SSH known hosts test.
* Ran tests multiple times and confirmed that the URL was included in the test output

Add ssh.dev.azure.com as remote hosts test candidate

---

pom.xml

Ran `mvn clean verify -Dtest=InjectedTest` and verified that the MINA plugin version in the dependency tree was the same as before this PR.

Require Jenkins 2.504.1 and remove unnecessary workaround

---

pom.xml

Do not allow additions to the bundled dependencies without a change to the list of bundledArtifacts.  Avoid the mistakes made in the past when a new transitive dependency was inadvertently added to the plugin and bundled into the hpi / jpi file.
Draft until the release of pull request:
* https://github.com/jenkinsci/maven-hpi-plugin/pull/771
Confirmed that compilation passes and a single test passes.  Rely on ci.jenkins.io for more complete testing

Explicitly declare bundled artifacts

---

CONTRIBUTING.adoc
Jenkinsfile
src/main/java/org/jenkinsci/plugins/gitclient/ChangelogCommand.java
src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
src/main/java/org/jenkinsci/plugins/gitclient/GitClient.java
src/main/java/org/jenkinsci/plugins/gitclient/JGitAPIImpl.java
src/test/java/org/jenkinsci/plugins/gitclient/GitAPITest.java
src/test/java/org/jenkinsci/plugins/gitclient/JGitAPIImplUnsupportedProtocolTest.java

Jenkins plugin BOM line 2.492.x needs the change that supports command line git 2.51.0.  That needs a release of the git client plugin stable-6.1 line.  Include the fix for SECURITY-3590 as well so that the vulnerability is fixed for the 2.492.x line.
Backported from pull requests:
* https://github.com/jenkinsci/git-client-plugin/pull/1326
* https://github.com/jenkinsci/git-client-plugin/pull/1327
The fix for SECURITY-3590 is cherry picked from 20090a86c3ebc72e5283c882de73e3a4459137bb
Confirmed that automated tests pass.
Confirmed interactively that SECURITY-3590 is visible without this change and that it is fixed with this change.
Confirmed interactively that change generation fails on command line git 2.51.0 without this change and succeeds with this change.

Support command line git 2.51.0
